default:
  document:
    author: "Kuangying Yang"
  Sample_number: 1
  tumor_type: "Tumor" # " PDX" or  "Tumor"
  Path: "/Users/hirbea/Desktop/Kuangying/Thesis/RNAseq/MPNST_PDX_drug"
  Email: "kuangyingyang@wustl.edu"
  Reference_path: "/Users/hirbea/Desktop/Kuangying/Thesis/RNAseq/MPNST_PDX_drug/Reference"
  base_output_dir: "/Users/hirbea/Desktop/Kuangying/Thesis/RNAseq/MPNST_PDX_drug/Report"
  Rawdata_path: "/Users/hirbea/Desktop/Kuangying/Thesis/RNAseq/MPNST_PDX_drug/Rawdata"
  Processed_path: "/Users/hirbea/Desktop/Kuangying/Thesis/RNAseq/MPNST_PDX_drug/Processed_data"
  drug: "HDACi"
  
   
