---
title: "Ex1 Phospho proteomics"
output: html_document
---

Preliminary summary




```{r include=FALSE}
library(MSnSet.utils)
library(dplyr)
library(ggplot2)
library(readxl)
library(synapser)
synapser::synLogin()

global_crosstab <- read.table(synapser::synGet("syn62178096")$path)

meta <- read_excel("../proteomics/data/PDX Proteomics Exp1 metadata.xlsx") 
# add unique identifier
meta$Tube <- paste(meta$PDX, meta$Drug, meta$`Time point (hr)`, "hr", sep = "_")
tube.types <- unique(meta$Tube)
for (i in 1:length(tube.types)) {
  meta[meta$Tube == tube.types[i],]$Tube <- paste0(meta[meta$Tube == tube.types[i],]$Tube, "_rep", seq(1, nrow(meta[meta$Tube == tube.types[i],])))
}
meta <- as.data.frame(meta)
rownames(meta) <- sub("-", ".", meta$Tube)
rownames(meta) <- sub("-", ".", rownames(meta)) # there are two dashes in JH-2-002 samples
meta$Treatment <- paste0(meta$Drug, " (", meta$`Time point (hr)`, " hrs)")
colnames(meta)[5] <- "Plex"
meta$Plex <- as.character(meta$Plex)

```


Missing data


```{r}
global_missing <- rowSums(is.na(global_crosstab))

hist(global_missing)

## 50 % missingness filter
global_crosstab <- global_crosstab[global_missing < ncol(global_crosstab)/2, ]

```

Raw data stats.


```{r}
## row medians
hist(apply(global_crosstab, 1, median, na.rm = T))

global_row_medians <- apply(global_crosstab, 1, median, na.rm = T)

global_crosstab <- sweep(global_crosstab, 1, global_row_medians, FUN = '-')

```



```{r}
## sample medians
hist(apply(global_crosstab, 2, median, na.rm = T))

## Using global coefficients to normalize phospho.
global_sample_coef <- apply(global_crosstab, 2, median, na.rm = T)

global_crosstab <- sweep(global_crosstab, 2, global_sample_coef, FUN = '-')

```



```{r}
m_global <- MSnSet(exprs = global_crosstab %>% as.matrix(), 
                   pData = meta[colnames(global_crosstab), ])

```


Both datasets show strong batch effect


```{r}
dir.create("PCA")
dir.create("before_plex_correction_w_mouse_rat")
temp.path <- "PCA/before_plex_correction_w_mouse_rat/"
phenos <- c("Plex", "Tube", "PDX", "Drug", "Time point (hr)", "Treatment")
for (i in 1:length(phenos)) {
  plot_pca(m_global, phenotype = phenos[i]) + ggtitle("Global PCA")
  ggsave(paste0(temp.path, "Chr8_UMN1_global_PCA_by_", phenos[i], "_w_mouse_rat_", Sys.Date(), ".pdf"))
}

```


```{r}
m_global_corrected <- correct_batch_effect_NA(m_global, "Plex", par.prior = T)

```



```{r PCAs human}
dir.create("PCA/after_plex_correction_w_mouse_rat")
temp.path <- "PCA/after_plex_correction_w_mouse_rat/"
phenos <- c("Plex", "Tube", "PDX", "Drug", "Time point (hr)", "Treatment")
for (i in 1:length(phenos)) {
  plot_pca(m_global_corrected, phenotype = phenos[i]) + ggtitle("Global PCA")
  ggsave(paste0(temp.path, "Chr8_UMN1_global_PCA_by_", phenos[i], "_w_mouse_rat_", Sys.Date(), ".pdf"))
}


# also filter to focus on specific drug treatments, PDX
PDXs <- unique(meta$PDX)
PDXs <- PDXs[!grepl("reference", PDXs, ignore.case = TRUE)]
drugs <- na.omit(unique(meta$Drug))
for (i in drugs) {
  dir.create(file.path(temp.path, i))
  temp.path2 <- file.path(temp.path, i)
  
  drug.meta <- na.omit(meta[meta$Drug == "DMSO" | meta$Drug == i,])
  drug.samples <- rownames(drug.meta)
  drug_global <- MSnSet(exprs = exprs(m_global_corrected)[, drug.samples], 
                   pData = meta[drug.samples, ])
  
  for (k in 1:length(phenos)) {
  plot_pca(drug_global, phenotype = phenos[k]) + ggtitle("Global PCA")
  ggsave(paste0(temp.path2, "/Chr8_UMN1_global_PCA_by_", phenos[k], "_", Sys.Date(), ".pdf"))
  }
  
  # also filter for each PDX
  for (j in PDXs) {
    dir.create(file.path(temp.path2, j))
    temp.path3 <- file.path(temp.path2, j) 
    
    drug.pdx.samples <- rownames(na.omit(drug.meta[drug.meta$PDX == j,]))
    drug_pdx_global <- MSnSet(exprs = exprs(m_global_corrected)[, drug.pdx.samples], 
                   pData = meta[drug.pdx.samples, ])
    
    for (k in 1:length(phenos)) {
      plot_pca(drug_pdx_global, phenotype = phenos[k]) + ggtitle("Global PCA")
      ggsave(paste0(temp.path3, "/Chr8_UMN1_global_PCA_by_", phenos[k], "_", Sys.Date(), ".pdf"))
    }
  }
}

# PCAs with better format / groupings
dir.create("PCA_ggplot_w_mouse_rat")
setwd("PCA_ggplot_w_mouse_rat")
# global
# make sure there's no missing data for PCAs
global.df <- exprs(m_global_corrected)
complete.global <- as.matrix(global.df[rowSums(is.na(global.df)) == 0,])

# set titles
global.title <- paste0("Global Proteomics (", nrow(complete.global), " out of ", nrow(global.df), " Proteins Represented)")

meta$Replicate <- substr(meta$Tube, nchar(meta$Tube), nchar(meta$Tube))
meta$id2 <- rownames(meta)

# run PCA
combo.pca.df <- data.frame(prcomp(t(complete.global))$x)
combo.pca.df$id2 <- rownames(combo.pca.df)
combo.pca.df2 <- merge(combo.pca.df, meta)

# plot PCA
abs.max <- ceiling(max(abs(c(combo.pca.df2$PC1, combo.pca.df2$PC2))))
global.pca <- ggplot2::ggplot(combo.pca.df2, aes(x=PC1, y=PC2, size = `Time point (hr)`, color = PDX, shape = Drug, label = Replicate)) + 
  geom_point() + theme_bw() + xlim(-abs.max, abs.max) + ylim(-abs.max, abs.max) +
  theme(text=element_text(size=20)) +
  labs(title= global.title)
ggplot2::ggsave(paste0("Global_PCA_8.5x12_equalAxisLimits_textSize20_", Sys.Date(), ".pdf"), global.pca, width = 12, height = 8.5)

```


Push to synapse.

```{r}
write.table(exprs(m_global_corrected), 
            file = "data/global_data_w_MOUSE_RAT_20240816/Chr8_UMN1_crosstab_global_prot_corrected.txt",
            quote=F, sep="\t")

```

```{r}
temp.df <- exprs(m_global_corrected)
message(length(rownames(temp.df)[startsWith(rownames(temp.df), "NP_")]), " human proteins")
message(length(rownames(temp.df)[endsWith(rownames(temp.df), "_MOUSE")]), " mouse proteins")
message(length(rownames(temp.df)[endsWith(rownames(temp.df), "_RAT")]), " rat proteins")
```

```{r}
plex_global <- limma_gen(m_global, "~Plex", "Plex")

plex_global_corrected <- limma_gen(m_global_corrected, "~Plex", "Plex")


```



```{r}
hist(plex_global$P.Value)
hist(plex_global_corrected$P.Value)

```


