---
title: "GSEA"
author: "Belinda B. Garana"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
if (!require(panSEA)) {
  if (!require("devtools", quietly = TRUE))
  install.packages("devtools")
  
  devtools::install_github("BelindaBGarana/panSEA", "add-tie-handling")
}

library(plyr);library(dplyr);library(ggplot2); library(patchwork)
library(synapser);library(panSEA); library(data.table); 
library(RColorBrewer); library(ComplexHeatmap)

```

## load inputs
```{r load inputs, echo = FALSE}
synapser::synLogin()
# RNA-seq data with HGNC symbols
diffexp <- read.csv(synapser::synGet('syn64397743')$path)
diffexp <- na.omit(diffexp[diffexp$hgnc_symbol!="",
                           c("hgnc_symbol", "log2FoldChange", "Drug", 
                             "Timepoint")])
diffexp$log2FoldChange <- as.numeric(diffexp$log2FoldChange)
diffexp <- diffexp[diffexp$Drug != "Irinotecan",] # since irinotecan isn't metabolically active

# get gene sets: Hallmark (H)
gmt.Hallmark <- as.data.frame(msigdbr::msigdbr(collection = "H"))
gmt.Hallmark <- DMEA::as_gmt(gmt.Hallmark, element.names="gene_symbol", set.names="gs_name") # 196 gene sets
saveRDS(gmt.Hallmark,"gmt_Hallmark.rds")
```

## run GSEA
```{r GSEA, echo = FALSE}
# GSEA NES > 0: pathways up-regulated in treated vs. untreated samples
synapse_id <- "syn65916546"
timepoints <- na.omit(unique(diffexp$Timepoint))
base.path <- getwd()
gsea.path <- file.path(base.path, "GSEA_Hallmark")
dir.create("GSEA_Hallmark")

gsea <- list()
for (i in timepoints) {
  # filter for time
  time.deg <- diffexp[diffexp$Timepoint == i,]
  
  # prep inputs for each drug
  drug.diffexp <- list()
  hall.gmts <- list()
  all.drugs <- na.omit(unique(time.deg$Drug))
  for (j in all.drugs) {
    temp.deg <- na.omit(dplyr::distinct(
      time.deg[time.deg$Drug == j,c("hgnc_symbol","log2FoldChange")]))
    colnames(temp.deg) <- c("Gene", "Log2FC")
    if (any(duplicated(temp.deg$Gene))) {
      temp.deg <- plyr::ddply(temp.deg, .(Gene), summarize,
                              Log2FC = mean(Log2FC))
    }
    drug.diffexp[[j]] <- temp.deg
    hall.gmts[[j]] <- gmt.Hallmark
  }
  
  # also run analysis for each drug
  hallResults <- panSEA::mGSEA(drug.diffexp, gmt=hall.gmts,
                               types = names(drug.diffexp))
  temp.gsea.df <- hallResults$compiled.results$result
  temp.gsea.df$Collection <- "Hallmark"
  colnames(temp.gsea.df)[1] <- "DrugTreatment"
  gsea[[as.character(i)]] <- temp.gsea.df
}
setwd(gsea.path)
gsea.df <- data.table::rbindlist(gsea, use.names=TRUE, idcol="Time")
write.csv(gsea.df,"GSEA_results_Hallmark.csv", row.names = FALSE)
synapser::synStore(synapser::File("GSEA_results_Hallmark.csv", parent=synapse_id))
```

### plot number of enriched pathways
```{r plot # of results, echo = FALSE}
# prep data
drug.info <- list("Palbociclib" = "CDK inhibitor", "Ribociclib" = "CDK inhibitor",
                  "Trabectedin" = "Chemotherapy", "Ifosfamide" = "DNA alkylating agent",
                  "Decitabine" = "DNMT inhibitor", "Vorinostat" = "HDAC inhibitor",
                  "Mirdametinib" = "MEK inhibitor", "Selumetinib" = "MEK inhibitor",
                  "Trametinib" = "MEK inhibitor", "Capmatinib" = "MET inhibitor",
                  "Olaparib" = "PARP inhibitor", "RMC4630" = "SHP2 inhibitor",
                  "TNO155" = "SHP2 inhibitor", "Doxorubicin" = "TOP inhibitor",
                  "Irinotecan" = "TOP inhibitor", "Verteporfin" = "YAP inhibitor")
base.path <- getwd()
gsea.path <- file.path(base.path, "GSEA_Hallmark")
setwd(gsea.path)
gsea.df <- read.csv("GSEA_results_Hallmark.csv")
gsea.df$Gene_set <- sub("HALLMARK_","",gsea.df$Feature_set)
gsea.df$DrugTreatment <- factor(gsea.df$DrugTreatment, levels=names(drug.info))
gsea.df$Time <- factor(gsea.df$Time, levels=c("8h","24h"))
all.drugs <- levels(gsea.df$DrugTreatment)
all.drugs <- all.drugs[all.drugs %in% gsea.df$DrugTreatment]
all.pathways <- sort(unique(unlist(drug.info[names(drug.info) %in% gsea.df$DrugTreatment])))
drugCol <- colorRampPalette(RColorBrewer::brewer.pal(length(all.drugs),"Set3"))(length(all.drugs)) # need color ramp for >12 colors
names(drugCol) <- all.drugs

sig.gsea <- gsea.df[gsea.df$FDR_q_value < 0.25 & 
                           gsea.df$p_value < 0.05,]
npathways.overall <- plyr::ddply(sig.gsea, .(DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Gene_set))))

# are there more/less enriched pathways at 8h vs. 24h? No: p-value = 0.2927817
cat("Overall", "# of pathways enriched at 8h vs. 24h\n")
t.test(npathways.overall[npathways.overall$Time=="8h",]$N,
       npathways.overall[npathways.overall$Time=="24h",]$N)
npathways.overall$pathway <- NA
for (i in all.pathways) {
  temp.drugs <- names(drug.info[drug.info %in% i])
  if (any(npathways.overall$DrugTreatment %in% temp.drugs)) {
   npathways.overall[npathways.overall$DrugTreatment %in% temp.drugs,]$pathway <- i
  }
}

# generate plot
npathways.overall$pathway <- factor(npathways.overall$pathway, levels=sort(na.omit(unique(npathways.overall$pathway))))
npathway.plot.overall <- ggplot2::ggplot(npathways.overall, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=pathway)) +
  geom_boxplot(width=0.2, alpha = 0) + scale_color_manual(limits=all.drugs, values=drugCol) +
  labs(x="Time (Hours)", y="# of Enriched Pathways",
       color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:length(all.pathways), breaks=all.pathways) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("N_enrichedPathways_overall.pdf", npathway.plot.overall, width=5.5, height=4)
```

### plot all enriched pathways
```{r plot all results, echo = FALSE}
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)
topSets <- unique(gsea.df[gsea.df$sig,]$Gene_set)
mean.results <- plyr::ddply(gsea.df, .(Gene_set), summarize,
                            NES = mean(NES, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$NES),]$Gene_set

dot.df <- gsea.df
dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Gene_set, color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=all.drugs) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  theme_minimal(base_size=12) +
  ggplot2::labs(color = "NES", size = "-log(FDR)") + 
  theme(axis.title=element_blank(), 
        axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
  facet_grid(.~Time)
dot.plot
# most are only in prot and not in RNA
ggplot2::ggsave("enrichedPathways_dotPlot.pdf", dot.plot, width=10, height=8) 
```

### plot top enriched pathways
```{r plot top results, echo = FALSE}
library(plyr);library(dplyr);library(ggplot2); library(poolr)
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)

# pathway.info2 <- dplyr::distinct(npathways[,c("DrugTreatment","pathway")])
# # create tile plot for drug pathway annotations
#   pathway.plot <- ggplot2::ggplot(pathway.info2, aes(x=DrugTreatment,y=1, fill=pathway)) + 
#   geom_tile() + scale_x_discrete(limits=all.drugs) + theme_classic(base_size=12) +
#   theme(axis.ticks=element_blank(), axis.text = element_blank(), axis.title=element_blank(),
#         axis.line=element_blank()) + labs(fill="Drug Mechanism")
# ggplot2::ggsave("MOA_annotations.pdf", pathway.plot, width=6,height=3)

n.top.list <- c(1, 2, 3, 5)
for (n.top in n.top.list) {
  ### top result(s) for each drug
  topSigpathway <- data.frame()
  for (i in all.drugs) {
    tempSig <- gsea.df[gsea.df$DrugTreatment == i &
                              gsea.df$sig,] %>% slice_max(abs(NES), n=n.top)
    topSigpathway <- rbind(topSigpathway, tempSig)
  }
  length(unique(topSigpathway$Gene_set)) # 20
  dot.df <- gsea.df[gsea.df$Gene_set %in% unique(topSigpathway$Gene_set),]
  
  mean.results <- plyr::ddply(dot.df, .(Gene_set), summarize,
                              NES = mean(NES, na.rm=TRUE))
  setOrder <- mean.results[order(mean.results$NES),]$Gene_set
  drugOrder <- unlist(drug.info)
  
  dot.df$Time <- factor(dot.df$Time, levels=timepoints)
  if (any(dot.df$FDR_q_value == 0)) {
    dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
  }
  dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
  dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
  maxAbsNES <- ceiling(max(abs(dot.df$NES)))
  dot.plot <- ggplot2::ggplot(
    na.omit(dot.df),
    ggplot2::aes(
      x = DrugTreatment, y = Gene_set, color = NES,
      size = minusLogFDR
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::scale_y_discrete(limits = setOrder) +
    ggplot2::scale_x_discrete(limits=all.drugs) +
    scale_color_gradient2(low="blue",high="red", mid="grey", 
                          limits=c(-maxAbsNES, maxAbsNES)) +
    theme_minimal(base_size=12) +
    ggplot2::labs(color = "NES", size = "-log(FDR)") + 
    theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1),
          axis.title = element_blank()) +
    geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
    facet_grid(.~Time)
  dot.plot
  ggplot2::ggsave(paste0(n.top,"_topEnrichedPathways_dotPlot.pdf"), dot.plot, width=10, height=ifelse(n.top<2,2,n.top))
  ggplot2::ggsave(paste0(n.top,"_topEnrichedPathways_dotPlot_taller.pdf"), dot.plot, width=10, height=ifelse(n.top<2,4,2*n.top))
  ggplot2::ggsave(paste0(n.top,"_topEnrichedPathways_dotPlot_Wider.pdf"), dot.plot, width=12, height=ifelse(n.top<2,2,n.top))
}
```

### plot top enriched pathways for each drug MOA
```{r plot top results per MOA, echo = FALSE}
library(plyr);library(dplyr);library(ggplot2)
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)

n.top.list <- c(1, 2, 3, 5)
for (moa in all.pathways) {
  temp.drugs <- names(drug.info[drug.info == moa])
  for (n.top in n.top.list) {
    ### pathway
    topSigpathway <- data.frame()
    for (i in temp.drugs) {
      tempSig <- gsea.df[gsea.df$DrugTreatment == i &
                           gsea.df$sig,] %>% slice_max(abs(NES), n=n.top)
      topSigpathway <- rbind(topSigpathway, tempSig)
    }
    length(unique(topSigpathway$Gene_set)) # 20
    dot.df <- gsea.df[gsea.df$Gene_set %in% unique(topSigpathway$Gene_set) &
                        gsea.df$DrugTreatment %in% temp.drugs,]
    if (nrow(dot.df) > 0) {
      mean.results <- plyr::ddply(dot.df, .(Gene_set), summarize,
                                  NES = mean(NES, na.rm=TRUE))
      setOrder <- mean.results[order(mean.results$NES),]$Gene_set
      drugOrder <- unlist(drug.info)
      
      dot.df$Time <- factor(dot.df$Time, levels=timepoints)
      if (any(dot.df$FDR_q_value == 0)) {
        dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
      }
      dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
      dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
      maxAbsNES <- ceiling(max(abs(dot.df$NES)))
      dot.plot <- ggplot2::ggplot(
        na.omit(dot.df),
        ggplot2::aes(
          x = DrugTreatment, y = Gene_set, color = NES,
          size = minusLogFDR
        )
      ) +
        ggplot2::geom_point() +
        ggplot2::scale_y_discrete(limits = setOrder) +
        ggplot2::scale_x_discrete(limits=temp.drugs) +
        scale_color_gradient2(low="blue",high="red", mid="grey", 
                              limits=c(-maxAbsNES, maxAbsNES)) +
        #viridis::scale_color_viridis() +
        theme_minimal(base_size=12) +
        ggplot2::labs(color = "NES", size = "-log(FDR)") + 
        theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1),
              axis.title = element_blank()) +
        geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21)
      if (length(unique(dot.df$Time)) > 0) {
        dot.plot <- dot.plot + facet_grid(.~Time)
      }
      dot.plot
      customWidth <- ifelse(length(temp.drugs) < 3, 4, length(temp.drugs)+2.5)
      ggplot2::ggsave(paste0(moa, "_",n.top,"_topEnrichedPathways_dotPlot.pdf"), 
                      dot.plot, width=customWidth, height=ifelse(n.top<2,2,n.top/2)) 
      ggplot2::ggsave(paste0(moa, "_",n.top,"_topEnrichedPathways_dotPlot_wider.pdf"), 
                      dot.plot, width=customWidth+2, height=ifelse(n.top<2,2,n.top/2))
    }
  } 
}
```


### upset plots to see overlap across drug treatments
```{r plot overlap of results, echo = FALSE}
library(ComplexHeatmap)
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)
gsea.df <- read.csv("GSEA_results_Hallmark.csv")
# inspired by: https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#upset-making-the-plot
# moa.info2 <- moa.info2[order(unique(unlist(drug.info))),]
# myCol <- as.list(RColorBrewer::brewer.pal(length(drug.info), "Set3"))
# names(myCol) <- names(drug.info)
# moaAnnotation <- ComplexHeatmap::HeatmapAnnotation(Mechanism = moa.info2$moa, col = myCol, which="row")

# generate list of significant results
sigList <- list()
for (i in unique(names(drug.info))) {
  if (nrow(gsea.df[gsea.df$DrugTreatment == i & gsea.df$sig,]) > 0) {
    sigList[[i]] <- na.omit(unique(gsea.df[gsea.df$DrugTreatment == i & 
                                                  gsea.df$sig,]$Gene_set)) 
  }
}

if (length(sigList) > 1) {
  # convert to matrix
  myPlot = ComplexHeatmap::make_comb_mat(sigList)
  #ComplexHeatmap::UpSet(m, right_annotation = moaAnnotation)
  pdf(file.path(gsea.path,"enrichedPathway_upsetPlot.pdf"))
  up <- ComplexHeatmap::UpSet(myPlot)
  draw(up)
  dev.off()
}

# repeat for upregulated pathways
sigList <- list()
for (i in unique(names(drug.info))) {
  if (nrow(gsea.df[gsea.df$DrugTreatment == i & gsea.df$sig,]) > 0) {
    sigList[[i]] <- na.omit(unique(gsea.df[gsea.df$DrugTreatment == i & 
                                                  gsea.df$sig & gsea.df$NES>0,]$Gene_set)) 
  }
}

if (length(sigList) > 1) {
  # convert to matrix
  myPlot = ComplexHeatmap::make_comb_mat(sigList)
  #ComplexHeatmap::UpSet(m, right_annotation = moaAnnotation)
  pdf(file.path(gsea.path,"upregulatedPathway_upsetPlot.pdf"))
  up <- ComplexHeatmap::UpSet(myPlot)
  draw(up)
  dev.off()
}

# repeat for downregulated pathways
sigList <- list()
for (i in unique(names(drug.info))) {
  if (nrow(gsea.df[gsea.df$DrugTreatment == i & gsea.df$sig,]) > 0) {
    sigList[[i]] <- na.omit(unique(gsea.df[gsea.df$DrugTreatment == i & 
                                                  gsea.df$sig & gsea.df$NES<0,]$Gene_set)) 
  }
}

if (length(sigList) > 1) {
  # convert to matrix
  myPlot = ComplexHeatmap::make_comb_mat(sigList)
  #ComplexHeatmap::UpSet(m, right_annotation = moaAnnotation)
  pdf(file.path(gsea.path,"downregulatedPathway_upsetPlot.pdf"))
  up <- ComplexHeatmap::UpSet(myPlot)
  draw(up)
  dev.off()
}
```

### correlations
```{r correlations, echo=FALSE}
library(RColorBrewer);library(pheatmap)
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)
gsea.df <- read.csv("GSEA_results_Hallmark.csv")
genemat<-gsea.df[gsea.df$FDR_q_value < 0.25 & 
                           gsea.df$p_value < 0.05,]|>
  dplyr::select(Gene_set,NES,DrugTreatment,Time)|>
  subset(!is.na(NES))|> 
  tidyr::unite(Time,DrugTreatment,col='condition')|>
  tidyr::pivot_wider(names_from=condition,values_from=NES,values_fn=mean,values_fill=0.0)|>
  tibble::column_to_rownames('Gene_set')|>
  as.matrix()
genecor<-cor(genemat,use='pairwise.complete.obs')
write.csv(genecor,"sigGSEACorr.csv")

annot <- as.data.frame(rownames(genecor)) |> 
  tidyr::separate('rownames(genecor)',into=c('Timepoint','Drug'),sep='_')
drug.info <- list("Palbociclib" = "CDK inhibitor", "Ribociclib" = "CDK inhibitor",
                  "Trabectedin" = "Chemotherapy", "Ifosfamide" = "DNA alkylating agent",
                  "Decitabine" = "DNMT inhibitor", "Vorinostat" = "HDAC inhibitor",
                  "Mirdametinib" = "MEK inhibitor", "Selumetinib" = "MEK inhibitor",
                  "Trametinib" = "MEK inhibitor", "Capmatinib" = "MET inhibitor",
                  "Olaparib" = "PARP inhibitor", "RMC4630" = "SHP2 inhibitor",
                  "TNO155" = "SHP2 inhibitor", "Doxorubicin" = "TOP inhibitor",
                  "Irinotecan" = "TOP inhibitor")
drug.info.df <- as.data.frame(t(as.data.frame(drug.info)))
drug.info.df$Drug <- rownames(drug.info.df)
colnames(drug.info.df)[1] <- "MOA"
annot <- merge(annot, drug.info.df, by="Drug", all.x=TRUE)
rownames(annot) <- paste0(annot$Timepoint, "_", annot$Drug)
annot <- annot[rownames(genecor),c('Timepoint','Drug','MOA')]
annot$Timepoint <- factor(annot$Timepoint, levels=c("8h","24h"))
annot$MOA <- factor(annot$MOA, levels=unique(annot$MOA))
annot$Drug <- factor(annot$Drug, levels=unique(annot$Drug))
cols=c(brewer.pal(8,'Dark2'),brewer.pal(15-8,'Set2'))
names(cols) <- names(drug.info)
cols <- cols[levels(annot$Drug)]
moa.cols <- RColorBrewer::brewer.pal(length(unique(annot$MOA)),"Set3")
names(moa.cols) <- levels(annot$MOA)
annot.colors = list(MOA = moa.cols,
                    Drug = cols,
                    Timepoint = c("8h" = "#FFFFFF", "24h" = "#000000"))

graphics.off()
pdf("sigGSEACorr.pdf",width=6,height=4.5)
pheatmap(genecor, annotation_row=annot, annotation_col=annot, annotation_colors=annot.colors,
         show_colnames=FALSE, show_rownames=FALSE)
dev.off()

genemat<-gsea.df|>
  dplyr::select(Gene_set,NES,DrugTreatment,Time)|>
  subset(!is.na(NES))|> 
  tidyr::unite(Time,DrugTreatment,col='condition')|>
  tidyr::pivot_wider(names_from=condition,values_from=NES,values_fn=mean,values_fill=0.0)|>
  tibble::column_to_rownames('Gene_set')|>
  as.matrix()
genecor<-cor(genemat,use='pairwise.complete.obs')
write.csv(genecor,"GSEACorr.csv")
graphics.off()
pdf("GSEACorr.pdf",width=6,height=4.5)
pheatmap(genecor, annotation_row=annot, annotation_col=annot, annotation_colors=annot.colors,
         show_colnames=FALSE, show_rownames=FALSE)
dev.off()
```

```{r shared results MEK and HDAC, echo=FALSE}
library(ggplot2); library(synapser)
synapser::synLogin()
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)
gsea.df <- read.csv(synapser::synGet("syn69910859")$path)
gsea.df$Gene_set <- sub("HALLMARK_","",gsea.df$Feature_set)

# find pathways enriched in both MEKi and HDACi at the same times in the same mpnsts
mek.hdac.sig <- c()
for (t in unique(gsea.df$Time)) {
  for (m in unique(gsea.df$MPNST)) {
    mek.sig <- unique(gsea.df[gsea.df$DrugTreatment %in% 
                                c("Mirdametinib","Trametinib","Selumetinib") &
                                gsea.df$sig & gsea.df$Time==t &
                                gsea.df$MPNST==m,]$Gene_set)
    hdac.sig <- unique(gsea.df[gsea.df$DrugTreatment =="Vorinostat" &
                                 gsea.df$sig & gsea.df$Time==t &
                                gsea.df$MPNST==m,]$Gene_set)
    mek.hdac.sig <- unique(c(mek.hdac.sig,mek.sig[mek.sig %in% hdac.sig]))
  }
}
dot.df <- gsea.df[gsea.df$DrugTreatment %in% 
                      c("Mirdametinib","Vorinostat","Trametinib","Selumetinib") &
                      gsea.df$Gene_set %in% mek.hdac.sig,]

dot.df$Time <- factor(dot.df$Time, levels=c("8h","24h"))
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = reorder(Gene_set,NES), color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_x_discrete(limits=c("Vorinostat","Mirdametinib","Selumetinib","Trametinib")) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(color = "NES", size = "-log(FDR)") + 
  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1),
        axis.title = element_blank()) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) + facet_grid(MPNST~Time)
dot.plot
customWidth <- ifelse(4 < 3, 4, 4+2.5)
ggplot2::ggsave("MEK_HDAC_Pathways_dotPlot_MPNST.pdf", 
                dot.plot, width=customWidth, 
                height=ifelse(length(mek.hdac.sig)<2,2,length(mek.hdac.sig)/2)) 
```

```{r shared results mirda and vorin, echo=FALSE}
library(ggplot2); library(synapser)
synapser::synLogin()
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)
gsea.df <- read.csv(synapser::synGet("syn69910859")$path)
gsea.df$Gene_set <- sub("HALLMARK_","",gsea.df$Feature_set)

# find pathways enriched in both MEKi and HDACi at the same times in the same mpnsts
mek.hdac.sig <- c()
for (t in unique(gsea.df$Time)) {
  for (m in unique(gsea.df$MPNST)) {
    mek.sig <- unique(gsea.df[gsea.df$DrugTreatment =="Mirdametinib" &
                                gsea.df$sig & gsea.df$Time==t &
                                gsea.df$MPNST==m,]$Gene_set)
    hdac.sig <- unique(gsea.df[gsea.df$DrugTreatment =="Vorinostat" &
                                 gsea.df$sig & gsea.df$Time==t &
                                gsea.df$MPNST==m,]$Gene_set)
    mek.hdac.sig <- unique(c(mek.hdac.sig,mek.sig[mek.sig %in% hdac.sig]))
  }
}
dot.df <- gsea.df[gsea.df$DrugTreatment %in% 
                      c("Mirdametinib","Vorinostat") &
                      gsea.df$Gene_set %in% mek.hdac.sig,]

dot.df$Time <- factor(dot.df$Time, levels=c("8h","24h"))
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = reorder(Gene_set,NES), color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_x_discrete(limits=c("Mirdametinib","Vorinostat")) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(color = "NES", size = "-log(FDR)") + 
  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1),
        axis.title = element_blank()) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) + facet_grid(MPNST~Time)
dot.plot
customWidth <- ifelse(4 < 3, 4, 4+2.5)
ggplot2::ggsave("mirdaVorin_Pathways_dotPlot_MPNST.pdf", 
                dot.plot, width=5, 
                height=ifelse(length(mek.hdac.sig)<2,2,length(mek.hdac.sig)/1.5)) 

dot.df <- gsea.df[gsea.df$DrugTreatment %in% 
                      c("Mirdametinib","Vorinostat") &
                      gsea.df$Gene_set %in% c("KRAS_SIGNALING_DN",
                                              "TNFA_SIGNALING_VIA_NFKB"),] # these pathways had opposite enrichment

dot.df$Time <- factor(dot.df$Time, levels=c("8h","24h"))
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = reorder(Gene_set,NES), color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_x_discrete(limits=c("Mirdametinib","Vorinostat")) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(color = "NES", size = "-log(FDR)") + 
  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1),
        axis.title = element_blank()) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) + facet_grid(MPNST~Time)
dot.plot
customWidth <- ifelse(4 < 3, 4, 4+2.5)
ggplot2::ggsave("mirdaVorin_oppPathways_dotPlot_MPNST.pdf", 
                dot.plot, width=5, 
                height=3.5)
```

```{r expression of leading edge genes opposite in mirda and vorin, echo=FALSE}
kras.leads <- unique(unlist(strsplit(gsea.df[gsea.df$DrugTreatment %in% c("Mirdametinib","Vorinostat") &
                                          gsea.df$sig &
                                            gsea.df$Gene_set=="KRAS_SIGNALING_DN",
                                          ]$Leading_edge, ", "))) # 109
tnfa.leads <- unique(unlist(strsplit(gsea.df[gsea.df$DrugTreatment %in% c("Mirdametinib","Vorinostat") &
                                          gsea.df$sig & gsea.df$Gene_set == "TNFA_SIGNALING_VIA_NFKB",
                                          ]$Leading_edge, ", "))) # 171
leads <- unique(c(kras.leads, tnfa.leads)) # 276
overlapping.leads <- kras.leads[kras.leads %in% tnfa.leads] # 4: NR4A2, EDN1, SGK1, BTG2
de <- read.csv(synapser::synGet("syn69910880")$path)
de.leads <- leads[leads %in% de[de$Drug %in% c("Mirdametinib","Vorinostat") & de$signif,]$hgnc_symbol] # 179
map.leads <- de.leads[startsWith(de.leads,"MAP2K")] # MAP2K3
hdac.leads <- de.leads[startsWith(de.leads,"HDAC")] # none
overlap.de.leads <- overlapping.leads[overlapping.leads %in% de.leads] # 3: NR4A2, EDN1, SGK1

mek.targets <- na.omit(unique(de[startsWith(de$hgnc_symbol,"MAP2K"),]$hgnc_symbol)) # 8
hdac.target <- na.omit(unique(de[startsWith(de$hgnc_symbol,"HDAC"),]$hgnc_symbol)) # 15
library(PCSF)
data("STRINGv12")
edges <- STRINGv12[STRINGv12$from %in% de.leads |
                          STRINGv12$to %in% de.leads,]
vert <- data.frame(unique(c(edges$from, edges$to)), type="Inferred", meanLog2FC=NA, sigMirda=NA, sigVorin=NA)
colnames(vert)[1] <- "name"
vert[vert$name %in% kras.leads,]$type <- "KRAS_SIGNALING_DN"
vert[vert$name %in% tnfa.leads,]$type <- "TNFA_SIGNALING_VIA_NFKB"
quant.nodes <- unique(vert$name[vert$name %in% de$hgnc_symbol]) # 6688 out of 7496
for (i in quant.nodes) {
  vert[vert$name == i,]$meanLog2FC <- mean(de[de$hgnc_symbol==i,]$log2FoldChange, na.rm=TRUE)
  vert[vert$name == i,]$sigMirda <- any(de[de$hgnc_symbol==i & de$Drug=="Mirdametinib",]$signif)
  vert[vert$name == i,]$sigVorin <- any(de[de$hgnc_symbol==i & de$Drug=="Vorinostat",]$signif)
}
vert$Target <- FALSE
vert[startsWith(vert$name,"HDAC"),]$Target <- TRUE
vert[startsWith(vert$name,"MAP2K"),]$Target <- TRUE
write.csv(vert,"mirdaVorin_diffexpLeads_nodes.csv", row.names=FALSE)
vert2 <- na.omit(vert[vert$sigMirda & vert$sigVorin,])
write.csv(vert2,"mirdaVorin_diffexpLeads_nodes_sigInBoth.csv", row.names=FALSE)
edges2 <- edges[edges$from %in% vert2$name,]
write.csv(vert2,"mirdaVorin_diffexpLeads_edges_sigInBoth.csv", row.names=FALSE)
vert3 <- vert[vert$name %in% c(edges2$from, edges2$to),]
write.csv(vert3,"mirdaVorin_diffexpLeads_nodes_sigInBoth_final.csv", row.names=FALSE)
topGraph <- igraph::graph_from_data_frame(edges2, directed=FALSE, vertices = vert3)
RCy3::createNetworkFromIgraph(topGraph, title="mirdaVen_diffexpLeads_sigInBoth")

edges3 <- edges2[edges2$from %in% vert3[vert3$Target,]$name,] # 167
vert4 <- vert[vert$name %in% c(edges3$from, edges3$to),] # 167
vert4$color <- "Inferred"
vert4[vert4$type=="TNFA_SIGNALING_VIA_NFKB",]$color <- "TNFA_SIGNALING_VIA_NFKB"
vert4[vert4$type=="KRAS_SIGNALING_DN",]$color <- "KRAS_SIGNALING_DN"
vert4[vert4$Target,]$color <- "Target"
vert4[vert4$Target & vert4$type=="TNFA_SIGNALING_VIA_NFKB",]$color <- "Target & TNFA_SIGNALING_VIA_NFKB" # noticed MAP2K3 was both

vert4$shape <- "Inferred"
vert4[!is.na(vert4$sigMirda) & vert4$sigMirda=="TRUE",]$shape <- "Affected by mirdametinib"
vert4[!is.na(vert4$sigVorin) & vert4$sigVorin=="TRUE",]$shape <- "Affected by vorinostat"
vert4[!is.na(vert4$sigVorin) & !is.na(vert4$sigMirda) & 
        vert4$sigVorin=="TRUE" & vert4$sigMirda=="TRUE",]$shape <- "Affected by mirdametinib & vorinostat"
topGraph <- igraph::graph_from_data_frame(edges3, directed=FALSE, vertices = vert4)
RCy3::createNetworkFromIgraph(topGraph, title="mirdaVen_diffexpLeads_sigInBoth_target")
write.csv(vert4, "mirdaVen_diffexpLeads_sigInBoth_target_nodes.csv", row.names=FALSE)
write.csv(edges3, "mirdaVen_diffexpLeads_sigInBoth_target_edges.csv", row.names=FALSE)

```

``` {r shared / unique results, echo=FALSE}
library(ggplot2); library(synapser); library(plyr);library(dplyr)
synapser::synLogin()
gsea.path <- file.path(getwd(),"GSEA_Hallmark")
setwd(gsea.path)
gsea.df <- read.csv("GSEA_results_Hallmark.csv")
gsea.df$Gene_set <- sub("HALLMARK_","",gsea.df$Feature_set)
print(length(unique(na.omit(gsea.df[gsea.df$sig,]$Gene_set))))

# add MOAs
drug.info <- list("Palbociclib" = "CDK inhibitor", "Ribociclib" = "CDK inhibitor",
                  "Trabectedin" = "Chemotherapy", "Ifosfamide" = "DNA alkylating agent",
                  "Decitabine" = "DNMT inhibitor", "Vorinostat" = "HDAC inhibitor",
                  "Mirdametinib" = "MEK inhibitor", "Selumetinib" = "MEK inhibitor",
                  "Trametinib" = "MEK inhibitor", "Capmatinib" = "MET inhibitor",
                  "Olaparib" = "PARP inhibitor", "RMC4630" = "SHP2 inhibitor",
                  "TNO155" = "SHP2 inhibitor", "Doxorubicin" = "TOP inhibitor",
                  "Verteporfin" = "YAP inhibitor")
red.drug.info <- drug.info[names(drug.info) %in% gsea.df$DrugTreatment]
gsea.df$moa <- NA
for (i in names(red.drug.info)) {
  gsea.df[gsea.df$DrugTreatment==i,]$moa <- red.drug.info[[i]]
}

n.sig <- plyr::ddply(gsea.df[gsea.df$sig,], .(Gene_set), summarize,
                     N_drugs=length(sort(unique(na.omit(DrugTreatment)))),
                     Drugs = paste0(sort(unique(na.omit(DrugTreatment))), collapse=", "),
                     N_moas=length(sort(unique(na.omit(moa)))),
                     moas = paste0(sort(unique(na.omit(moa))), collapse=", "),
                     N_drugs_up=length(sort(unique(na.omit(DrugTreatment[NES>0])))),
                     Drugs_up = paste0(sort(unique(na.omit(DrugTreatment[NES>0]))), collapse=", "),
                     N_moas_up=length(sort(unique(na.omit(moa[NES>0])))),
                     moas_up = paste0(sort(unique(na.omit(moa[NES>0]))), collapse=", "),
                     N_drugs_dn=length(sort(unique(na.omit(DrugTreatment[NES<0])))),
                     Drugs_dn = paste0(sort(unique(na.omit(DrugTreatment[NES<0]))), collapse=", "),
                     N_moas_dn=length(sort(unique(na.omit(moa[NES<0])))),
                     moas_dn = paste0(sort(unique(na.omit(moa[NES<0]))), collapse=", "))
```