---
title: "DMEA_Cmap_L1000"
author: "Belinda B. Garana"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
if (require(panSEA)) {
  if (!require("devtools", quietly = TRUE))
  install.packages("devtools")
  
  devtools::install_github("BelindaBGarana/panSEA", "add-tie-handling")
}

library(plyr);library(dplyr);library(ggplot2);library(synapser);library(panSEA)
library(data.table)
source("https://raw.githubusercontent.com/PNNL-CompBio/MPNST_Chr8/refs/heads/main/panSEA_helper_20240913.R")

# load helper functions
# adapted from: https://github.com/PNNL-CompBio/coderdata/blob/main/build/lincs/05-LINCS_perturbations.R
build_L1000 <- function() {
  options(timeout = 300)

  # identify URLs
  #basename="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE101406"
  L1000 <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5FLevel4%5FZSPCINF%5Fmlr12k%5Fn1667x12328.gctx.gz'
  L1000.genes <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5Fgene%5Finfo.txt.gz'
  L1000.inst <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5Finst%5Finfo.txt.gz'

  # download source sample & perturbation info
  L1000.genes.info <- readr::read_delim(L1000.genes, "\t") # pr_gene_symbol, pr_gene_id
  L1000.inst.info <- readr::read_delim(L1000.inst, "\t") # pert_iname; pert_type = "trt_cp" if drug, "ctl_vehicle" if DMSO; cell_id
  L1000.inst.info <- L1000.inst.info[L1000.inst.info$pert_type == "trt_cp", ] # only keep drug treatments (remove DMSO controls)

  # download L1000 data
  if (file.exists("L1000.gctx")) {
    L1000.df <- cmapR::parse_gctx("L1000.gctx")
  } else {
   res<-download.file(L1000,'L1000.gctx.gz', mode="wb")
  L1000.df<-cmapR::parse_gctx(R.utils::gunzip("L1000.gctx.gz")) 
  }

  # put data into long format
  L1000.long <- cmapR::melt_gct(L1000.df)
  colnames(L1000.long) <- c("inst_id", "pr_gene_id", "data_value")
  L1000.long$pr_gene_id <- as.numeric(L1000.long$pr_gene_id)

  # join with L1000.gene.info based on pr_gene_id;
  # L1000.inst.info based on inst_id;
  # keep only cell_id, pert_type, pert_iname, gene_symbol, data_value
  L1000.full <- L1000.long |>
    dplyr::left_join(L1000.genes.info) |>
    dplyr::left_join(L1000.inst.info) |>
    dplyr::select(cell_id,pert_type,pert_iname,pr_gene_symbol,data_value)|>
    dplyr::distinct()
  L1000.long <- NULL # save space

  # add relevant columns
  L1000.full <- na.omit(L1000.full)
  colnames(L1000.full)[1] <- "other_names" # match samples column name
  colnames(L1000.full)[4] <- "gene_symbol" # match genes column name
  colnames(L1000.full)[3] <- "chem_name"
  L1000.full$data_type <- "transcriptomics"
  L1000.full$source <- "Broad"
  L1000.full$study <- "LINCS"
  L1000.full$perturbation_type <- "drug" # all entries have pert_type="trt_cp"
  return(L1000.full)
}
```

## load inputs
```{r load inputs, echo = FALSE}
synapser::synLogin()
# RNA-seq data with HGNC symbols (update once batch-corrected)
diffexp <- read.csv(synapser::synGet('syn64397743')$path)
degs <- na.omit(diffexp)#[diffexp$padj <= 0.05,])
degs$log2FoldChange <- as.numeric(degs$log2FoldChange)
if (any(degs$drug=="Ribociblib")) {
 degs[degs$drug=="Ribociblib",]$drug <- "Ribociclib" 
}

# reduce to overlapping genes, check for overlapping drugsL1000.genes <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5Fgene%5Finfo.txt.gz'
L1000.genes <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5Fgene%5Finfo.txt.gz'
L1000.genes.info <- readr::read_delim(L1000.genes, "\t") # pr_gene_symbol, pr_gene_id
degs.L1000 <- degs[degs$hgnc_symbol %in% L1000.genes.info$pr_gene_symbol,] # 46337 / 62734
# noticed Cmap L1000 Query also tags the following as invalid genes: "C14orf132","C3orf18"
# search degs and noticed anything containing "orf" (usually C[numbers]orf[numbers]) was invalid
degs.L1000 <- degs.L1000[!grepl("orf",degs.L1000$hgnc_symbol),]
```

## produce GMTs
```{r produce txt files, echo = FALSE}
drug.info <- list("CDK inhibitor" = c("Palbociclib","Ribociclib"),
                  "Chemotherapy" = "Trabectidin",
                  "DNA alkylating agent" = "Ifosfamide",
                  "DNA methyltransferase inhibitor" = "Decitabine",
                  "HDAC inhibitor" = "Vorinostat",
                  "MEK inhibitor" = c("Mirdametinib","Selumetinib","Trametinib"),
                  "MET inhibitor" = "Capmatinib",
                  "PARP inhibitor" = "Olaparib",
                  "SHP2 inhibitor" = c("RMC4630","TNO155"),
                  "topoisomerase inhibitor" = c("Doxorubicin","Irinotecan"),
                  "TEADi" = "Verteporfin")
# compare treated vs. untreated
# DMEA NES < 0: drug mechanisms which may be more toxic to treated samples
timepoints <- na.omit(unique(degs.L1000$Timepoint))
mpnst <- na.omit(unique(degs.L1000$individualID))
base.path <- getwd()
dmea.path <- file.path(base.path, "DMEA_Cmap_L1000")
dir.create("DMEA_Cmap_L1000")

old.degs <- read.csv(file.path(base.path,"DMEA_Cmap_L1000_sigOnly/Top_150_DEGs_by_absLog2FC_noTies.csv"))
all.drug.degs <- data.frame()
for (i in timepoints) {
  # filter for time
  time.deg <- degs.L1000[degs.L1000$Timepoint == i,]
  old.time.deg <- old.degs[old.degs$Timepoint == i,]
  
  temp.dmea.sens <- list()
  temp.drug.corr.sens <- list()
  for (m in mpnst) {
    # filter for mpnst
    mpnst.deg <- time.deg[time.deg$individualID == m,]
    old.mpnst.deg <- old.time.deg[old.time.deg$individualID == m,]
    # prep inputs for each drug
    drug.degs <- list()
    #expr <- list()
    all.drugs <- na.omit(unique(mpnst.deg$Drug))
    for (j in all.drugs) {
      temp.deg <- na.omit(dplyr::distinct(
        mpnst.deg[mpnst.deg$Drug == j,c("hgnc_symbol","log2FoldChange")]))
      colnames(temp.deg) <- c("Gene", "Log2FC")
      if (any(duplicated(temp.deg$Gene))) {
        temp.deg <- plyr::ddply(temp.deg, .(Gene), summarize,
                                Log2FC = mean(Log2FC))
      }
      #temp.deg <- temp.deg[temp.deg$Gene %in% colnames(ccle)[2:ncol(ccle)],]
      if (nrow(temp.deg) > 0) {
        old.temp.deg <- old.mpnst.deg[old.mpnst.deg$Drug == j,]
        up.deg <- temp.deg[temp.deg$Log2FC>0,] %>% slice_max(Log2FC, n=150, with_ties=FALSE)
        old.up.deg <- old.temp.deg[old.temp.deg$Log2FC > 0,]
        dn.deg <- temp.deg[temp.deg$Log2FC<0,] %>% slice_min(Log2FC, n=150, with_ties=FALSE)
        old.up.deg <- old.temp.deg[old.temp.deg$Log2FC > 0,]
        if (nrow(up.deg) >= 10 & nrow(dn.deg) >= 10) {
          temp.drug.degs <- rbind(up.deg, dn.deg)
          temp.drug.degs$redo <- TRUE
          if (identical(sort(up.deg$Gene), sort(old.up.deg$Gene)) &
              identical(sort(dn.deg$Gene), sort(old.dn.deg$Gene))) {
            temp.drug.degs$redo <- FALSE
          }
          drug.degs[[j]] <- temp.drug.degs 
        }
      }
    }
    drug.degs.df <- data.table::rbindlist(drug.degs, use.names=TRUE, idcol="DrugTreatment")
    drug.degs.df$Time <- substr(i,1,nchar(i)-1)
    drug.degs.df$MPNST <- m
    all.drug.degs <- rbind(all.drug.degs, drug.degs.df)
  } 
}
setwd(dmea.path)
write.csv(all.drug.degs,"Top_150_DEGs_by_absLog2FC_noTies.csv", row.names = FALSE)
```

### compile results
```{r compile results, echo=FALSE}
dmea.path <- file.path(getwd(), "DMEA_Cmap_L1000")
setwd(dmea.path)
all.drug.degs <- read.csv("Top_150_DEGs_by_absLog2FC_noTies.csv")
timepoints <- na.omit(unique(all.drug.degs$Time))
mpnst <- na.omit(unique(all.drug.degs$MPNST))
cmap.outputs <- list()
outputs <- list()
inputs <- list()

for (i in timepoints) {
  temp.cmap.outputs <- list()
  temp.outputs <- list()
  temp.inputs <- list()
  for (m in mpnst) {
    setwd(dmea.path)
    cmap.results <- list()
    moa.results <- list()
    drug.list <- list()
    for (j in na.omit(unique(all.drug.degs$DrugTreatment))) {
      fname <- paste0("Query_results/",m,"_",as.character(i),"h_",j,"_Cmap_L1000_Query.tar.gz")
      if (file.exists(fname)) {
        ## get Cmap MOA results
        cat(file=stderr(), "About to load", fname, "\n")
        dir.info <- archive::archive_extract(fname)
        dir.name <- dir.info[1]
        fname2 <- "gsea/TAG/arfs/NORM_CS/gsea_result.gct" # this points to Cmap MOA results
        fname3 <- paste0(dir.name, fname2)
        rank.data <- read.delim(file=archive::archive_extract(fname, files=fname3), skip = 2)
        rank.data <- rank.data[rank.data$cell_iname=="-666" & rank.data$pert_type=="TRT_CP" &
                                 (rank.data$set_type=="PCL" | rank.data$set_type=="MOA_CLASS"),]
        cmap.results[[j]] <- rank.data[,c("id","raw_cs","norm_cs","fdr_q_nlog10")]
        
        ## get drug ranks
        # load file
        fname2 <- "arfs/TAG/query_result.gct" # this points to Cmap MOA results
        fname3 <- paste0(dir.name, fname2)
        rank.data <- read.delim(file=archive::archive_extract(fname, files=fname3), skip = 2)
        
        # filter drug list
        cat(file=stderr(), "About to filter input", "\n")
        rank.data <- rank.data[rank.data$qc_pass==1,]
        rank.data <- rank.data[rank.data$pert_iname!="na",] # removes empty first row in CMap query output
        rank.data <- rank.data[rank.data$moa!="-666",] # remove drugs without known moa (moa="-666")
        rank.data[,ncol(rank.data)] <- as.numeric(rank.data[,ncol(rank.data)]) # assuming rank metric is last column
        rank.data <- rank.data[rank.data[,ncol(rank.data)]!=0,]
        rank.metric <- colnames(rank.data)[ncol(rank.data)] # store name of rank metric to restore later
        
        # average rank metric
        cat(file=stderr(), "About to average rank metric", "\n")
        rank.data$FDR_q_value <- 10^(-as.numeric(rank.data$fdr_q_nlog10))
        rank.data <- plyr::ddply(rank.data, .(pert_iname, moa), summarize, norm_cs = mean(as.numeric(norm_cs), na.rm=TRUE),
                                 FDR_q_value = ifelse(length(na.omit(FDR_q_value))==1,na.omit(FDR_q_value), 
                                                      as.numeric(metap::sumlog(na.omit(FDR_q_value))$p))) #average across cell lines
        rank.data$fdr_q_nlog10 <- -log(rank.data$FDR_q_value, 10)
        drug.list[[j]] <- dplyr::distinct(na.omit(rank.data[!duplicated(rank.data[,c("pert_iname")]),]))
        rank.data <- dplyr::distinct(na.omit(rank.data[!duplicated(rank.data[,c("pert_iname")]), c("pert_iname", "norm_cs", "moa")]))
        
        # run DMEA
        cat(file=stderr(), "About to run enrichment analysis", "\n")
        DMEA.output <- panSEA::drugSEA_ties(rank.data, drug="pert_iname", rank.metric="norm_cs",
                                            FDR=0.25, min.per.set=6, ties=FALSE)
        moa.results[[j]] <- DMEA.output$result
      }
    }  
    temp.cmap.outputs[[m]] <- data.table::rbindlist(cmap.results, use.names = TRUE, idcol="DrugTreatment")
    temp.outputs[[m]] <- data.table::rbindlist(moa.results, use.names = TRUE, idcol="DrugTreatment")
    temp.inputs[[m]] <- data.table::rbindlist(drug.list, use.names = TRUE, idcol="DrugTreatment") 
  }
  cmap.outputs[[as.character(i)]] <- data.table::rbindlist(temp.cmap.outputs, use.names = TRUE, idcol="MPNST")
  outputs[[as.character(i)]] <- data.table::rbindlist(temp.outputs, use.names = TRUE, idcol="MPNST")
  inputs[[as.character(i)]] <- data.table::rbindlist(temp.inputs, use.names = TRUE, idcol="MPNST")
}
cmap.dmea.sens.df <- data.table::rbindlist(cmap.outputs, use.names = TRUE, idcol = "Time")
drug.corr.sens.df <- data.table::rbindlist(inputs, use.names = TRUE, idcol="Time")
dmea.sens.df <- data.table::rbindlist(outputs, use.names = TRUE, idcol = "Time")
write.csv(cmap.dmea.sens.df, "Cmap_L1000_moaRanks.csv", row.names = FALSE)
write.csv(drug.corr.sens.df, "Cmap_L1000_drugRanks.csv", row.names = FALSE)
write.csv(dmea.sens.df, "DMEA_Cmap_L1000.csv", row.names = FALSE)
dmea.files <- list("Cmap_L1000_drugRanks.csv" = drug.corr.sens.df,
                   "Cmap_L1000_moaRanks.csv" = cmap.dmea.sens.df,
                   "DMEA_Cmap_L1000.csv" = dmea.sens.df)
synapse_id <- "syn64693139"
synapser::synLogin()
save_to_synapse_v2(dmea.files, synapse_id)
```

### plot number of correlated drugs, enriched MOAs
```{r plot # of results, echo = FALSE}
## drug mechanisms
# prep data
library(plyr);library(dplyr);library(ggplot2);library(patchwork)
setwd(dmea.path)
dmea.sens.df <- read.csv("DMEA_Cmap_L1000.csv")
drug.corr.sens.df <- read.csv("Cmap_L1000_drugRanks.csv")
dmea.sens.df$Time <- paste0(dmea.sens.df$Time, "h")
dmea.sens.df$Time <- factor(dmea.sens.df$Time, levels=c("8h", "24h"))
sig.dmea <- dmea.sens.df[dmea.sens.df$FDR_q_value <= 0.25 & 
                           dmea.sens.df$p_value <= 0.05,]
nMOAs <- plyr::ddply(sig.dmea, .(MPNST, DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Drug_set))))
nMOAs.overall <- plyr::ddply(sig.dmea, .(DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Drug_set))))

# are there more/less enriched drug MOAs at 8h vs. 24h? Yes, more at 8h; p = 0.03234
# for (m in mpnst) {
#  cat(m, "# of MOAs enriched at 8h vs. 24h\n")
#   t.test(nMOAs[nMOAs$MPNST==m & nMOAs$Time=="8h",]$N, 
#          nMOAs[nMOAs$MPNST==m & nMOAs$Time=="24h",]$N) 
# }
cat("Overall", "# of MOAs enriched at 8h vs. 24h\n")
t.test(nMOAs.overall[nMOAs.overall$Time=="8h",]$N, 
       nMOAs.overall[nMOAs.overall$Time=="24h",]$N)

nMOAs$moa <- NA
nMOAs.overall$moa <- NA
for (i in 1:length(drug.info)) {
  if (any(nMOAs$DrugTreatment %in% drug.info[[i]])) {
   nMOAs[nMOAs$DrugTreatment %in% drug.info[[i]],]$moa <- names(drug.info)[i] 
   nMOAs.overall[nMOAs.overall$DrugTreatment %in% drug.info[[i]],]$moa <- names(drug.info)[i]
  }
}

# generate plot
nMOAs$moa <- factor(nMOAs$moa, levels=sort(na.omit(unique(nMOAs$moa))))
nMOA.plot <- ggplot2::ggplot(nMOAs, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=moa)) +
  geom_boxplot(width=0.2, alpha = 0) + 
  scale_color_manual(limits=all.drugs, values=drugCol) +
  labs(x="Time (Hours)", y="# of Enriched Drug Mechanisms",
       color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:length(all.moas), breaks=all.moas) + 
  theme_classic(base_size=12) +
  theme(legend.box="horizontal") + facet_wrap(~MPNST)
ggplot2::ggsave("N_enrichedDrugMechanisms.pdf", nMOA.plot, width=5.5, height=4)

nMOAs.overall$moa <- factor(nMOAs.overall$moa, levels=sort(na.omit(unique(nMOAs.overall$moa))))
nMOA.plot.overall <- ggplot2::ggplot(nMOAs.overall, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=moa)) +
  geom_boxplot(width=0.2, alpha = 0) + scale_color_manual(limits=all.drugs, values=drugCol) +
  labs(x="Time (Hours)", y="# of Enriched Drug Mechanisms",
       color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:length(all.moas), breaks=all.moas) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("N_enrichedDrugMechanisms_overall.pdf", nMOA.plot.overall, width=5.5, height=4)

## drugs
# prep data
drug.corr.sens.df$Time <- paste0(drug.corr.sens.df$Time, "h")
drug.corr.sens.df$Time <- factor(drug.corr.sens.df$Time, levels=c("8h", "24h"))
sig.drug.corr <- drug.corr.sens.df[drug.corr.sens.df$fdr_q_nlog10 >= -log10(0.05),]
nDrugs <- plyr::ddply(sig.drug.corr, .(MPNST, DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Drug))))
nDrugs.overall <- plyr::ddply(sig.drug.corr, .(DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Drug))))

# are there more/less correlated drugs at 8h vs. 24h? No: p-value = 0.5048
# for (m in mpnst) {
#  cat(m, "# of drugs correlated at 8h vs. 24h\n")
#   t.test(nDrugs[nDrugs$MPNST==m & nDrugs$Time=="8h",]$N, 
#          nDrugs[nDrugs$MPNST==m & nDrugs$Time=="24h",]$N) 
# }
# cat("Overall", "# of drugs correlated at 8h vs. 24h\n")
# t.test(nDrugs.overall[nDrugs.overall$Time=="8h",]$N, 
#        nDrugs.overall[nDrugs.overall$Time=="24h",]$N)

nDrugs$moa <- NA
nDrugs.overall$moa <- NA
for (i in 1:length(drug.info)) {
  if (any(nDrugs$DrugTreatment %in% drug.info[[i]])) {
   nDrugs[nDrugs$DrugTreatment %in% drug.info[[i]],]$moa <- names(drug.info)[i] 
   nDrugs.overall[nDrugs.overall$DrugTreatment %in% drug.info[[i]],]$moa <- names(drug.info)[i]
  }
}

# generate plot
#nDrugs$Time <- factor(nDrugs$Time, levels=timepoints)
nDrugs$moa <- factor(nDrugs$moa, levels=sort(na.omit(unique(nDrugs$moa))))
nDrug.plot <- ggplot2::ggplot(nDrugs, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=moa)) + scale_color_manual(limits=all.drugs, values=drugCol) +
  geom_boxplot(width=0.2, alpha = 0) + 
  scale_y_continuous(trans="log10") + labs(x="Time (Hours)", y="Log(# of Correlated Drugs)",
                                           color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:length(all.moas), breaks=all.moas) + theme_classic(base_size=12) +
  theme(legend.box="horizontal") + facet_wrap(~MPNST)
ggplot2::ggsave("N_correlatedDrugs.pdf", nDrug.plot, width=5.5, height=4)

#nDrugs.overall$Time <- factor(nDrugs.overall$Time, levels=timepoints)
nDrugs.overall$moa <- factor(nDrugs.overall$moa, levels=sort(na.omit(unique(nDrugs.overall$moa))))
nDrug.plot.overall <- ggplot2::ggplot(nDrugs, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=moa)) + scale_color_manual(limits=all.drugs, values=drugCol) +
  geom_boxplot(width=0.2, alpha = 0) + 
  scale_y_continuous(trans="log10") + labs(x="Time (Hours)", y="Log(# of Correlated Drugs)",
                                           color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:length(all.moas), breaks=all.moas) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("N_correlatedDrugs_overall.pdf", nDrug.plot.overall, width=5.5, height=4)

patchN.plot <- nMOA.plot + nDrug.plot + patchwork::plot_layout(guides="collect") #& theme(legend.box="horizontal")
ggplot2::ggsave("N_drugsAndMOAs.pdf", patchN.plot, width=8, height=4)
ggplot2::ggsave("N_drugsAndMOAs_taller.pdf", patchN.plot, width=8, height=8)

patchN.plot.overall <- nMOA.plot.overall + nDrug.plot.overall + patchwork::plot_layout(guides="collect") #& theme(legend.box="horizontal")
ggplot2::ggsave("N_drugsAndMOAs_overall.pdf", patchN.plot.overall, width=8, height=4)
ggplot2::ggsave("N_drugsAndMOAs_overall_taller.pdf", patchN.plot.overall, width=8, height=10)
```


### plot all enriched MOAs
```{r plot all results, echo = FALSE}
timepoints <- c("8h", "24h")
library(plyr);library(dplyr);library(ggplot2)
dmea.path <- file.path(getwd(),"DMEA_Cmap_L1000")
setwd(dmea.path)
dmea.sens.df$sig <- FALSE
dmea.sens.df[dmea.sens.df$p_value <= 0.05 & dmea.sens.df$FDR_q_value <= 0.25,]$sig <- TRUE
topSets <- unique(dmea.sens.df[dmea.sens.df$sig,]$Drug_set)
mean.results <- plyr::ddply(dmea.sens.df, .(Drug_set), summarize,
                            NES = mean(NES, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$NES),]$Drug_set
setFace <- rep("plain", length(setOrder))
names(setFace) <- setOrder
setFace[names(drug.info)] <- "bold"

drugsInTopSets <- unlist(drug.info[topSets])
tested.drugs <- na.omit(unique(dmea.sens.df$DrugTreatment))
drugsInTopSets <- drugsInTopSets[drugsInTopSets %in% tested.drugs]
inputDrugs <- unique(unlist(drug.info))[unique(unlist(drug.info)) %in% tested.drugs]
inputFace <- rep("plain", length(inputDrugs))
names(inputFace) <- inputDrugs
inputFace[drugsInTopSets] <- "bold"

dot.df <- dmea.sens.df#[dmea.sens.df$Drug_set %in% topSets,]
dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Drug_set, color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=names(inputFace)) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(
    x = "Drug Treatment (Input)",
    y = "Drug Mechanism (Output)",
    color = "NES", size = "-log(FDR)"
  ) + 
  theme(axis.text.y=element_text(face=setFace), 
        axis.text.x=element_text(face=inputFace,angle=45, vjust=1, hjust=1)) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
  facet_wrap(vars(cols = Time, rows=MPNST))
dot.plot
# most are only in prot and not in RNA
ggplot2::ggsave("Enriched_MOAs_dotPlot.pdf", dot.plot, width=10, height=20)

```


### plot top correlated drugs, enriched MOAs
```{r plot top results, echo = FALSE}
library(plyr);library(dplyr);library(ggplot2)
dmea.path <- file.path(getwd(),"DMEA_Cmap_L1000")
setwd(dmea.path)

moa.info2 <- dplyr::distinct(nMOAs[,c("DrugTreatment","moa")])

n.top.list <- c(1, 2, 3, 5)
for (n.top in n.top.list) {
  ### MOA
  topSigMOA <- data.frame()
  for (i in tested.drugs) {
    tempSig <- dmea.sens.df[dmea.sens.df$DrugTreatment == i &
                              dmea.sens.df$sig,] %>% slice_max(abs(NES), n=n.top)
    topSigMOA <- rbind(topSigMOA, tempSig)
  }
  length(unique(topSigMOA$Drug_set)) # 20
  dot.df <- dmea.sens.df[dmea.sens.df$Drug_set %in% unique(topSigMOA$Drug_set),]
  
  mean.results <- plyr::ddply(dot.df, .(Drug_set), summarize,
                              NES = mean(NES, na.rm=TRUE))
  setOrder <- mean.results[order(mean.results$NES),]$Drug_set
  drugOrder <- unlist(drug.info)
  
  dot.df$Time <- factor(dot.df$Time, levels=timepoints)
  if (any(dot.df$FDR_q_value == 0)) {
    dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
  }
  dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
  dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
  maxAbsNES <- ceiling(max(abs(dot.df$NES)))
  dot.plot <- ggplot2::ggplot(
    na.omit(dot.df),
    ggplot2::aes(
      x = DrugTreatment, y = Drug_set, color = NES,
      size = minusLogFDR
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::scale_y_discrete(limits = setOrder) +
    ggplot2::scale_x_discrete(limits=drugOrder) +
    scale_color_gradient2(low="blue",high="red", mid="grey", 
                          limits=c(-maxAbsNES, maxAbsNES)) +
    #viridis::scale_color_viridis() +
    theme_minimal(base_size=12) +
    ggplot2::labs(
      x = "Drug Treatment (Input)",
      y = "Drug Mechanism (Output)",
      color = "NES", size = "-log(FDR)"
    ) + 
    theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
    geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
    facet_wrap(vars(cols = Time, rows=MPNST))
  dot.plot
  ggplot2::ggsave(paste0(n.top,"_topEnrichedMOAs_dotPlot.pdf"), dot.plot, width=10, height=ifelse(n.top<2,4,2*n.top))
  
  # create tile plot for drug MOA annotations
  moa.plot <- ggplot2::ggplot(moa.info2, aes(x=DrugTreatment,y=1, fill=moa)) + 
  geom_tile() + scale_x_discrete(limits=drugOrder) + theme_classic(base_size=12) +
  theme(axis.ticks=element_blank(), axis.text = element_blank(), axis.title=element_blank(),
        axis.line=element_blank()) + labs(fill="Drug Mechanism")
ggplot2::ggsave("MOA_annotations.pdf", moa.plot, width=6,height=3)
  
  ### Drug correlations
  topSigDrug <- data.frame()
  for (i in tested.drugs) {
    tempSig <- drug.corr.sens.df[drug.corr.sens.df$DrugTreatment == i &
                                   drug.corr.sens.df$fdr_q_nlog10 >= -log10(0.05),] %>% slice_max(abs(norm_cs), n=n.top)
    topSigDrug <- rbind(topSigDrug, tempSig)
  }
  cat("Number of top correlated drugs:", length(unique(topSigDrug$pert_iname)))
  mean.results <- plyr::ddply(drug.corr.sens.df[drug.corr.sens.df$pert_iname %in% topSigDrug$pert_iname,], .(pert_iname), summarize,
                              norm_cs = mean(norm_cs, na.rm=TRUE))
  setOrder <- mean.results[order(mean.results$norm_cs),]$pert_iname
  
  dot.df <- drug.corr.sens.df#[drug.corr.sens.df$Drug %in% topSets,]
  dot.df$Time <- factor(dot.df$Time, levels=timepoints)
  maxAbsnorm_cs <- ceiling(max(abs(dot.df$norm_cs)))
  dot.plot <- ggplot2::ggplot(
    na.omit(dot.df),
    ggplot2::aes(
      x = DrugTreatment, y = pert_iname, color = norm_cs,
      size = fdr_q_nlog10
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::scale_y_discrete(limits = setOrder) +
    ggplot2::scale_x_discrete(limits=drugOrder) +
    scale_color_gradient2(low="blue",high="red", mid="grey", 
                          limits=c(-maxAbsnorm_cs, maxAbsnorm_cs)) +
    #viridis::scale_color_viridis() +
    theme_minimal(base_size=12) +
    ggplot2::labs(
      x = "Drug Treatment (Input)",
      y = "Drug (Output)",
      color = "Normalized Connectivity Score", size = "-log(FDR)"
    ) + 
    theme( 
      axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
    geom_point(data = subset(dot.df, fdr_q_nlog10 >= -log10(0.05)), col = "black", stroke = 1.5, shape = 21) +
    facet_wrap(vars(cols = Time, rows=MPNST))
  dot.plot
  # most are only in prot and not in RNA
  ggplot2::ggsave(paste0(n.top,"_topSimilarDrugs_dotPlot.pdf"), dot.plot, width=10, height=ifelse(4*n.top<5,5,4*n.top))
}

```


### plot validations
```{r plot validation results, echo = FALSE}

library(plyr);library(dplyr);library(ggplot2)
dmea.path <- file.path(getwd(),"DMEA_Cmap_L1000")
setwd(dmea.path)
### MOA
topSets <- names(drug.info)
sigTopSets <- topSets[topSets %in% dmea.sens.df[dmea.sens.df$sig,]$Drug_set]
validations <- data.frame()
for (i in names(drug.info)) {
  temp.valid <- dmea.sens.df[dmea.sens.df$Drug_set == i &
                               dmea.sens.df$DrugTreatment %in% drug.info[[i]] &
                               dmea.sens.df$sig,]
  validations <- rbind(validations, temp.valid)
}
validTopSets <- unique(validations$Drug_set)
mean.results <- plyr::ddply(dmea.sens.df[dmea.sens.df$Drug_set %in% topSets,], .(Drug_set), summarize,
                            NES = mean(NES, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$NES),]$Drug_set
setFace <- rep("plain", length(setOrder))
names(setFace) <- setOrder
setFace[validTopSets] <- "bold"

drugsInTopSets <- unlist(drug.info[topSets])
drugsInValidTopSets <- unlist(drug.info[validTopSets])
tested.drugs <- na.omit(unique(dmea.sens.df$DrugTreatment))
drugsInValidTopSets <- drugsInValidTopSets[drugsInValidTopSets %in% tested.drugs]
inputDrugs <- unique(unlist(drug.info))[unique(unlist(drug.info)) %in% tested.drugs]
inputFace <- rep("plain", length(inputDrugs))
names(inputFace) <- inputDrugs
inputFace[drugsInValidTopSets] <- "bold"

dot.df <- dmea.sens.df[dmea.sens.df$Drug_set %in% names(drug.info),]
dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Drug_set, color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=names(inputFace)) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(
    x = "Drug Treatment (Input)",
    y = "Drug Mechanism (Output)",
    color = "NES", size = "-log(FDR)"
  ) + 
  theme(axis.text.y=element_text(face=setFace), 
        axis.text.x=element_text(face=inputFace,
          angle=45, vjust=1, hjust=1),
        legend.box="horizontal") +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
  facet_wrap(vars(cols = Time,rows=MPNST))
dot.plot
# most are only in prot and not in RNA
ggplot2::ggsave("Validation_MOAs_dotPlot.pdf", dot.plot, width=10, height=3)

# also plot just sig validations as scatter plot over time
validations$Time <- as.character(validations$Time)
validations$Time <- as.numeric(substr(validations$Time, 1, nchar(validations$Time)-1))
validations$Drug_set <- factor(validations$Drug_set, levels=sort(na.omit(unique(validations$Drug_set))))
validation.plot <- ggplot2::ggplot(validations, aes(x=Time, y=NES, color=DrugTreatment)) + 
  geom_point(aes(shape=Drug_set, alpha=MPNST)) + geom_smooth(method="lm", se = FALSE, linetype="dashed") + #geom_line(linetype="dashed") +
  scale_x_continuous(trans="log10") +
  labs(x="Time (Hours)", y="Normalized Enrichment Score",
       color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:nlevels(validations$Drug_set)) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("validatedDrugMechanisms_scatterPlot.pdf", validation.plot, width=8, height=3)

### Drug correlations
drugValidations <- drug.corr.sens.df[tolower(drug.corr.sens.df$pert_iname) == tolower(drug.corr.sens.df$DrugTreatment) &
                                       drug.corr.sens.df$fdr_q_nlog10 >= -log10(0.05),] # 0
drugValidations$Time <- as.character(drugValidations$Time)
drugValidations$Time <- as.numeric(substr(drugValidations$Time, 1, nchar(drugValidations$Time)-1))
validation.plot <- ggplot2::ggplot(drugValidations, aes(x=Time, y=norm_cs, color=DrugTreatment)) + 
  geom_point(aes(shape=MPNST)) + geom_smooth(method="lm", se = FALSE, linetype="dashed") + #geom_line(linetype="dashed") +
  scale_x_continuous(trans="log10") +
  labs(x="Time (Hours)", y="Normalized Connectivity Score",
       color = "Drug Treatment", shape = "MPNST") + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("validatedDrugs_scatterPlot.pdf", validation.plot, width=5.5, height=3)
```


### upset plots to see overlap across drug treatments
```{r plot overlap of results, echo = FALSE}
dmea.path <- file.path(getwd(),"DMEA_Cmap_L1000")
setwd(dmea.path)
library(ComplexHeatmap)
# inspired by: https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#upset-making-the-plot
moa.info2 <- moa.info2[order(unique(unlist(drug.info))),]
myCol <- as.list(RColorBrewer::brewer.pal(length(drug.info), "Set3"))
names(myCol) <- names(drug.info)
moaAnnotation <- ComplexHeatmap::HeatmapAnnotation(Mechanism = moa.info2$moa, col = myCol, which="row")

for (m in mpnst) {
  # generate list of significant results
  sigList <- list()
  for (i in unique(unlist(drug.info))) {
    if (nrow(dmea.sens.df[dmea.sens.df$DrugTreatment == i & 
                          dmea.sens.df$MPNST == m & dmea.sens.df$sig,]) > 0) {
      sigList[[i]] <- na.omit(unique(dmea.sens.df[dmea.sens.df$DrugTreatment == i & 
                                                    dmea.sens.df$MPNST == m & dmea.sens.df$sig,]$Drug_set)) 
    }
  }
  
  if (length(sigList) > 1) {
    # convert to matrix
    myPlot = ComplexHeatmap::make_comb_mat(sigList)
    #ComplexHeatmap::UpSet(m, right_annotation = moaAnnotation)
    pdf(file.path(dmea.path,paste0(m,"_enrichedMOA_upsetPlot.pdf")))
    up <- ComplexHeatmap::UpSet(myPlot)
    draw(up)
    dev.off()
  }
}
# could also repeat for individual timepoints or filtered for "optimal" timepoints (max validation / inhibition of known targets) 
```