---
title: "DMEA_CCLE"
author: "Belinda B. Garana"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
if (require(panSEA)) {
  if (!require("devtools", quietly = TRUE))
  install.packages("devtools")
  
  devtools::install_github("BelindaBGarana/panSEA", "add-tie-handling")
}

library(plyr);library(dplyr);library(ggplot2);library(synapser);library(panSEA)
library(data.table)
source("https://raw.githubusercontent.com/PNNL-CompBio/MPNST_Chr8/refs/heads/main/panSEA_helper_20240913.R")

# load helper functions
#source("https://github.com/PNNL-CompBio/coderdata/blob/main/build/lincs/05-LINCS_perturbations.R")
get_CCLE_RNA <- function(hgnc = FALSE) {
  message("Loading adherent CCLE RNA-seq data version 19Q4")
  if (hgnc) {
    if (!file.exists("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_1-200.Rbin")) {
      download.file(
        paste0(
          "https://raw.github.com/BelindaBGarana/DMEA/shiny-app/Inputs/",
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_1-200.Rbin"
        ),
        destfile =
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_1-200.Rbin"
      )
    }
    
    if (!file.exists("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_201-327.Rbin")) {
      download.file(
        paste0(
          "https://raw.github.com/BelindaBGarana/DMEA/shiny-app/Inputs/",
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_201-327.Rbin"
        ),
        destfile =
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_201-327.Rbin"
      )
    }
    
    RNA.first200 <- readRDS("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_1-200.Rbin")
    RNA.rest <- readRDS("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_approved_symbols_only_201-327.Rbin")
    RNA.df <- rbind(RNA.first200, RNA.rest) 
  } else {
    if (!file.exists("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_1-200.Rbin")) {
      download.file(
        paste0(
          "https://raw.github.com/BelindaBGarana/DMEA/shiny-app/Inputs/",
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_1-200.Rbin"
        ),
        destfile =
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_1-200.Rbin"
      )
    }
    
    if (!file.exists("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_201-327.Rbin")) {
      download.file(
        paste0(
          "https://raw.github.com/BelindaBGarana/DMEA/shiny-app/Inputs/",
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_201-327.Rbin"
        ),
        destfile =
          "Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_201-327.Rbin"
      )
    }
    
    load("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_1-200.Rbin")
    load("Normalized_adherent_CCLE_RNAseq_19Q4_samples_in_PRISM_201-327.Rbin")
    RNA.df <- rbind(RNA.first200, RNA.rest) 
  }
  return(RNA.df)
}

# adapted from: https://github.com/PNNL-CompBio/coderdata/blob/main/build/lincs/05-LINCS_perturbations.R
build_L1000 <- function() {
  options(timeout = 300)

  # identify URLs
  #basename="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE101406"
  L1000 <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5FLevel4%5FZSPCINF%5Fmlr12k%5Fn1667x12328.gctx.gz'
  L1000.genes <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5Fgene%5Finfo.txt.gz'
  L1000.inst <- 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE101nnn/GSE101406/suppl/GSE101406%5FBroad%5FLINCS%5FL1000%5Finst%5Finfo.txt.gz'

  # download source sample & perturbation info
  L1000.genes.info <- readr::read_delim(L1000.genes, "\t") # pr_gene_symbol, pr_gene_id
  L1000.inst.info <- readr::read_delim(L1000.inst, "\t") # pert_iname; pert_type = "trt_cp" if drug, "ctl_vehicle" if DMSO; cell_id
  L1000.inst.info <- L1000.inst.info[L1000.inst.info$pert_type == "trt_cp", ] # only keep drug treatments (remove DMSO controls)

  # download L1000 data
  if (file.exists("L1000.gctx")) {
    L1000.df <- cmapR::parse_gctx("L1000.gctx")
  } else {
   res<-download.file(L1000,'L1000.gctx.gz', mode="wb")
  L1000.df<-cmapR::parse_gctx(R.utils::gunzip("L1000.gctx.gz")) 
  }

  # put data into long format
  L1000.long <- cmapR::melt_gct(L1000.df)
  colnames(L1000.long) <- c("inst_id", "pr_gene_id", "data_value")
  L1000.long$pr_gene_id <- as.numeric(L1000.long$pr_gene_id)

  # join with L1000.gene.info based on pr_gene_id;
  # L1000.inst.info based on inst_id;
  # keep only cell_id, pert_type, pert_iname, gene_symbol, data_value
  L1000.full <- L1000.long |>
    dplyr::left_join(L1000.genes.info) |>
    dplyr::left_join(L1000.inst.info) |>
    dplyr::select(cell_id,pert_type,pert_iname,pr_gene_symbol,data_value)|>
    dplyr::distinct()
  L1000.long <- NULL # save space

  # add relevant columns
  L1000.full <- na.omit(L1000.full)
  colnames(L1000.full)[1] <- "other_names" # match samples column name
  colnames(L1000.full)[4] <- "gene_symbol" # match genes column name
  colnames(L1000.full)[3] <- "chem_name"
  L1000.full$data_type <- "transcriptomics"
  L1000.full$source <- "Broad"
  L1000.full$study <- "LINCS"
  L1000.full$perturbation_type <- "drug" # all entries have pert_type="trt_cp"
  return(L1000.full)
}
```

## load inputs
```{r load inputs, echo = FALSE}
# Cmap L1000 data
degs <- build_L1000()
degs <- dplyr::distinct(na.omit(degs[,c("gene_symbol", "data_value", "chem_name")]))

# CCLE RNA-seq with HGNC symbols
ccle <- get_CCLE_RNA(hgnc = TRUE)

# reduce to overlapping genes
degs <- degs[degs$gene_symbol %in% colnames(ccle)[2:ncol(ccle)],] # 55746 genes
ccle <- ccle[,c("CCLE_ID", degs$gene_symbol)]

# PRISM drug sensitivity (i.e., AUC)
prism <- read.csv(file = paste0("https://raw.github.com/BelindaBGarana/",
        "DMEA/shiny-app/Inputs/PRISM_drug_mean_AUC_6-23-21.csv"))
prism$X <- NULL

# PRISM drug mechanism of action annotations
gmt.drug <- GSA::GSA.read.gmt(file = paste0(
          "https://raw.github.com/BelindaBGarana/DMEA/shiny-app/",
          "Inputs/MOA_gmt_file_n6_no_special_chars.gmt"))

```

## run DMEA
```{r DMEA, echo = FALSE}
# DMEA NES < 0: drug mechanisms which may be more toxic to treated samples
base.path <- getwd()
dmea.path <- file.path(base.path, "DMEA_CCLE")
dir.create("DMEA_CCLE")
setwd(dmea.path)

# prep inputs for each drug
drug.degs <- list()
expr <- list()
all.drugs <- na.omit(unique(degs$chem_name))
for (j in all.drugs) {
  temp.deg <- na.omit(dplyr::distinct(
    degs[degs$chem_name == j,c("gene_symbol","data_value")]))
  colnames(temp.deg) <- c("Gene", "Log2FC")
  if (any(duplicated(temp.deg$Gene))) {
    temp.deg <- plyr::ddply(temp.deg, .(Gene), summarize,
                            Log2FC = mean(Log2FC))
  }
  temp.deg <- temp.deg[temp.deg$Gene %in% colnames(ccle)[2:ncol(ccle)],]
  if (nrow(temp.deg) > 0) {
    drug.degs[[j]] <- temp.deg
    expr[[j]] <- ccle[,c("CCLE_ID", temp.deg$Gene)]
  }
}

# also run analysis for each drug
drugResults <- panSEA::mDMEA(drug.sensitivity = prism, gmt = gmt.drug,
                             expression = expr, weights = drug.degs,
                             types = names(drug.degs))
time.files <- list()
tested.drugs <- names(drugResults$all.results)
for (j in tested.drugs) {
  time.files[[j]] <- extract_DMEA_files(drugResults, j)
}
time.files[["Compiled"]] <- 
  list("DMEA_results.csv" = drugResults$compiled.results$results,
       "Compiled_DMEA_results.csv" = drugResults$compiled.results$mean.results,
       "DMEA_venn_diagram.pdf" = drugResults$compiled.results$venn.diagram,
       "DMEA_dot_plot.pdf" = drugResults$compiled.results$dot.plot,
       "DMEA_correlations.csv" = drugResults$compiled.results$corr,
       "DMEA_correlation_matrix.pdf" =drugResults$compiled.results$corr.matrix)
save_to_synapse_v2(time.files)

dmea.sens.df <- drugResults$compiled.results$result

# also compile drug correlations
drug.corr.list <- list()
for (j in tested.drugs) {
  drug.corr.list[[j]] <- drugResults$all.results[[j]]$corr.result
}
drug.corr.sens.df <- data.table::rbindlist(drug.corr.list, use.names = TRUE, idcol = "DrugTreatment")


setwd(dmea.path)

colnames(dmea.sens.df)[2] <- "DrugTreatment"
write.csv(dmea.sens.df,paste0("DMEA_results_",Sys.Date(),".csv"), row.names = FALSE)
write.csv(drug.corr.sens.df,paste0("DMEA_correlations_",Sys.Date(),".csv"), row.names = FALSE)
```

### plot number of correlated drugs, enriched MOAs
```{r plot # of results, echo = FALSE}
## drug mechanisms
# prep data
library(plyr);library(dplyr);library(ggplot2);library(patchwork)
setwd(dmea.path)
#dmea.sens.df <- read.csv(paste0("DMEA_results_","2025-02-13",".csv"))
#drug.corr.sens.df <- read.csv(paste0("DMEA_correlations_","2025-02-13",".csv"))
sig.dmea <- dmea.sens.df[dmea.sens.df$FDR_q_value <= 0.25 & 
                           dmea.sens.df$p_value <= 0.05,]
nMOAs <- plyr::ddply(sig.dmea, .(DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Drug_set))))

# are there more/less enriched drug MOAs at 8h vs. 24h? No: p-value = 0.967
cat("# of MOAs enriched at 8h vs. 24h")
t.test(nMOAs[nMOAs$Time=="8h",]$N, nMOAs[nMOAs$Time=="24h",]$N)

nMOAs$moa <- NA
for (i in 1:length(drug.info)) {
  if (any(nMOAs$DrugTreatment %in% drug.info[[i]])) {
   nMOAs[nMOAs$DrugTreatment %in% drug.info[[i]],]$moa <- names(drug.info)[i] 
  }
}

# generate plot
nMOAs$Time <- factor(nMOAs$Time, levels=timepoints)
nMOAs$moa <- factor(nMOAs$moa, levels=sort(na.omit(unique(nMOAs$moa))))
nMOA.plot <- ggplot2::ggplot(nMOAs, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=moa)) +
  geom_boxplot(width=0.2, alpha = 0) + 
  labs(x="Time (Hours)", y="# of Enriched Drug Mechanisms",
       color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:nlevels(nMOAs$moa)) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("N_enrichedDrugMechanisms.pdf", nMOA.plot, width=5.5, height=4)

## drugs
# prep data
sig.drug.corr <- drug.corr.sens.df[drug.corr.sens.df$Pearson.q <= 0.05,]
nDrugs <- plyr::ddply(sig.drug.corr, .(DrugTreatment, Time), dplyr::summarize,
                    N = length(na.omit(unique(Drug))))

# are there more/less correlated drugs at 8h vs. 24h? No: p-value = 0.549
cat("# of drugs correlated at 8h vs. 24h")
t.test(nDrugs[nDrugs$Time=="8h",]$N, nDrugs[nDrugs$Time=="24h",]$N)

nDrugs$moa <- NA
for (i in 1:length(drug.info)) {
  if (any(nDrugs$DrugTreatment %in% drug.info[[i]])) {
   nDrugs[nDrugs$DrugTreatment %in% drug.info[[i]],]$moa <- names(drug.info)[i] 
  }
}

# generate plot
nDrugs$Time <- factor(nDrugs$Time, levels=timepoints)
nDrugs$moa <- factor(nDrugs$moa, levels=sort(na.omit(unique(nDrugs$moa))))
nDrug.plot <- ggplot2::ggplot(nDrugs, aes(x=Time, y=N)) + geom_violin(alpha=0) +
  geom_point(aes(color=DrugTreatment, shape=moa)) +
  geom_boxplot(width=0.2, alpha = 0) + 
  scale_y_continuous(trans="log10") + labs(x="Time (Hours)", y="Log(# of Correlated Drugs)",
                                           color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:nlevels(nDrugs$moa)) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("N_correlatedDrugs.pdf", nDrug.plot, width=5.5, height=4)

patchN.plot <- nMOA.plot + nDrug.plot + patchwork::plot_layout(guides="collect") #& theme(legend.box="horizontal")
ggplot2::ggsave("N_drugsAndMOAs.pdf", patchN.plot, width=8, height=4)
ggplot2::ggsave("N_drugsAndMOAs_taller.pdf", patchN.plot, width=8, height=6)
```

### plot all correlated drugs, enriched MOAs
```{r plot all results, echo = FALSE}

library(plyr);library(dplyr);library(ggplot2)
dmea.path <- file.path(getwd(),"DMEA")
setwd(dmea.path)
#dmea.sens.df <- read.csv(paste0("DMEA_results_","2025-01-29",".csv"))
#drug.corr.sens.df <- read.csv(paste0("DMEA_correlations_","2025-01-29",".csv"))
### MOA
topSets <- unique(dmea.sens.df[dmea.sens.df$sig,]$Drug_set)
mean.results <- plyr::ddply(dmea.sens.df, .(Drug_set), summarize,
                            NES = mean(NES, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$NES),]$Drug_set
setFace <- rep("plain", length(setOrder))
names(setFace) <- setOrder
setFace[names(drug.info)] <- "bold"

drugsInTopSets <- unlist(drug.info[topSets])
tested.drugs <- na.omit(unique(dmea.sens.df$DrugTreatment))
drugsInTopSets <- drugsInTopSets[drugsInTopSets %in% tested.drugs]
inputDrugs <- unique(unlist(drug.info))[unique(unlist(drug.info)) %in% tested.drugs]
inputFace <- rep("plain", length(inputDrugs))
names(inputFace) <- inputDrugs
inputFace[drugsInTopSets] <- "bold"

dot.df <- dmea.sens.df#[dmea.sens.df$Drug_set %in% topSets,]
dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Drug_set, color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=names(inputFace)) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(
    x = "Drug Treatment (Input)",
    y = "Drug Mechanism (Output)",
    color = "NES", size = "-log(FDR)"
  ) + 
  theme(axis.text.y=element_text(face=setFace), 
        axis.text.x=element_text(face=inputFace,angle=45, vjust=1, hjust=1)) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
  facet_wrap(vars(cols = Time))
dot.plot
# most are only in prot and not in RNA
ggplot2::ggsave("Enriched_MOAs_dotPlot_facetTime.pdf", dot.plot, width=10, height=13)

### Drug correlations
topSets <- unique(drug.corr.sens.df[drug.corr.sens.df$sig,]$Drug)
mean.results <- plyr::ddply(drug.corr.sens.df, .(Drug), summarize,
                            Pearson.est = mean(Pearson.est, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$Pearson.est),]$Drug
setFace <- rep("plain", length(setOrder))
names(setFace) <- setOrder
setFace[names(drug.info)] <- "bold"


inputDrugs <- unique(unlist(drug.info))[unique(unlist(drug.info)) %in% tested.drugs]
inputFace <- rep("plain", length(inputDrugs))
names(inputFace) <- inputDrugs
inputFace[topSets] <- "bold"

dot.df <- drug.corr.sens.df#[drug.corr.sens.df$Drug %in% topSets,]
dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df$Pearson.p, base = 10)
dot.df$minusLogFDR <- -log(dot.df$Pearson.q, base = 10)
maxAbsPearson.est <- ceiling(max(abs(dot.df$Pearson.est)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Drug, color = Pearson.est,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=names(inputFace)) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsPearson.est, maxAbsPearson.est)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(
    x = "Drug Treatment (Input)",
    y = "Drug (Output)",
    color = "Pearson r", size = "-log(FDR)"
  ) + 
  theme(axis.text.y=element_text(face=setFace), 
        axis.text.x=element_text(face=inputFace,angle=45, vjust=1, hjust=1)) +
  geom_point(data = subset(dot.df, Pearson.q <= 0.05), col = "black", stroke = 1.5, shape = 21) +
  facet_wrap(vars(cols = Time))
dot.plot
# most are only in prot and not in RNA
ggplot2::ggsave("Correlated_drugs_dotPlot_facetTime.pdf", dot.plot, width=8, height=12)
```

### plot top correlated drugs, enriched MOAs
```{r plot top results, echo = FALSE}

library(plyr);library(dplyr);library(ggplot2)
dmea.path <- file.path(getwd(),"DMEA")
setwd(dmea.path)
#dmea.sens.df <- read.csv(paste0("DMEA_results_","2025-01-29",".csv"))
#drug.corr.sens.df <- read.csv(paste0("DMEA_correlations_","2025-01-29",".csv"))
### MOA
topSigMOA <- data.frame()
for (i in tested.drugs) {
  tempSig <- dmea.sens.df[dmea.sens.df$DrugTreatment == i &
                                 dmea.sens.df$sig,] %>% slice_max(abs(NES), n=5)
  topSigMOA <- rbind(topSigMOA, tempSig)
}
length(unique(topSigMOA$Drug_set)) # 20
dot.df <- dmea.sens.df[dmea.sens.df$Drug_set %in% unique(topSigMOA$Drug_set),]

mean.results <- plyr::ddply(dot.df, .(Drug_set), summarize,
                            NES = mean(NES, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$NES),]$Drug_set
drugOrder <- unlist(drug.info)

dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Drug_set, color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=drugOrder) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(
    x = "Drug Treatment (Input)",
    y = "Drug Mechanism (Output)",
    color = "NES", size = "-log(FDR)"
  ) + 
  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
  facet_wrap(vars(cols = Time))
dot.plot
ggplot2::ggsave("Top_5_enriched_MOAs_dotPlot_facetTime.pdf", dot.plot, width=10, height=4)

# create tile plot for MOA annotations
moa.info2 <- dplyr::distinct(nMOAs[,c("DrugTreatment","moa")])
moa.plot <- ggplot2::ggplot(moa.info2, aes(x=DrugTreatment,y=1, fill=moa)) + 
  geom_tile() + scale_x_discrete(limits=drugOrder) + theme_classic(base_size=12) +
  theme(axis.ticks=element_blank(), axis.text = element_blank(), axis.title=element_blank(),
        axis.line=element_blank()) + labs(fill="Drug Mechanism")
ggplot2::ggsave("MOA_annotations_Top_5_enriched_MOAs_dotPlot_facetTime.pdf", moa.plot, width=6,height=3)

### Drug correlations
n.top.list <- c(1, 2, 3, 5)
for (n.top in n.top.list) {
  topSigDrug <- data.frame()
  for (i in tested.drugs) {
    tempSig <- drug.corr.sens.df[drug.corr.sens.df$DrugTreatment == i &
                                   drug.corr.sens.df$Pearson.q <= 0.05,] %>% slice_max(abs(Pearson.est), n=n.top)
    topSigDrug <- rbind(topSigDrug, tempSig)
  }
  cat("Number of top correlated drugs:", length(unique(topSigDrug$Drug)))
  dot.df <- dmea.sens.df[dmea.sens.df$Drug %in% unique(topSigMOA$Drug_set),]
  mean.results <- plyr::ddply(drug.corr.sens.df[drug.corr.sens.df$Drug %in% topSigDrug$Drug,], .(Drug), summarize,
                              Pearson.est = mean(Pearson.est, na.rm=TRUE))
  setOrder <- mean.results[order(mean.results$Pearson.est),]$Drug
  
  dot.df <- drug.corr.sens.df#[drug.corr.sens.df$Drug %in% topSets,]
  dot.df$Time <- factor(dot.df$Time, levels=timepoints)
  if (any(dot.df$FDR_q_value == 0)) {
    dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
  }
  dot.df$minusLogP <- -log(dot.df$Pearson.p, base = 10)
  dot.df$minusLogFDR <- -log(dot.df$Pearson.q, base = 10)
  maxAbsPearson.est <- ceiling(max(abs(dot.df$Pearson.est)))
  dot.plot <- ggplot2::ggplot(
    na.omit(dot.df),
    ggplot2::aes(
      x = DrugTreatment, y = Drug, color = Pearson.est,
      size = minusLogFDR
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::scale_y_discrete(limits = setOrder) +
    ggplot2::scale_x_discrete(limits=drugOrder) +
    scale_color_gradient2(low="blue",high="red", mid="grey", 
                          limits=c(-maxAbsPearson.est, maxAbsPearson.est)) +
    #viridis::scale_color_viridis() +
    theme_minimal(base_size=12) +
    ggplot2::labs(
      x = "Drug Treatment (Input)",
      y = "Drug (Output)",
      color = "Pearson r", size = "-log(FDR)"
    ) + 
    theme( 
      axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
    geom_point(data = subset(dot.df, Pearson.q <= 0.05), col = "black", stroke = 1.5, shape = 21) +
    facet_wrap(vars(cols = Time))
  dot.plot
  # most are only in prot and not in RNA
  ggplot2::ggsave(paste0("Top_",n.top,"_correlated_drugs_dotPlot_facetTime.pdf"), dot.plot, width=10, height=10*n.top/5)
}

```


### plot validations
```{r plot validation results, echo = FALSE}

library(plyr);library(dplyr);library(ggplot2)
dmea.path <- file.path(getwd(),"DMEA")
setwd(dmea.path)
#dmea.sens.df <- read.csv(paste0("DMEA_results_","2025-01-26",".csv"))
#drug.corr.sens.df <- read.csv(paste0("DMEA_correlations_","2025-01-26",".csv"))
### MOA
topSets <- names(drug.info)
sigTopSets <- topSets[topSets %in% dmea.sens.df[dmea.sens.df$sig,]$Drug_set]
validations <- data.frame()
for (i in names(drug.info)) {
  temp.valid <- dmea.sens.df[dmea.sens.df$Drug_set == i &
                               dmea.sens.df$DrugTreatment %in% drug.info[[i]] &
                               dmea.sens.df$sig,]
  validations <- rbind(validations, temp.valid)
}
validTopSets <- unique(validations$Drug_set)
mean.results <- plyr::ddply(dmea.sens.df[dmea.sens.df$Drug_set %in% topSets,], .(Drug_set), summarize,
                            NES = mean(NES, na.rm=TRUE))
setOrder <- mean.results[order(mean.results$NES),]$Drug_set
setFace <- rep("plain", length(setOrder))
names(setFace) <- setOrder
setFace[validTopSets] <- "bold"

drugsInTopSets <- unlist(drug.info[topSets])
drugsInValidTopSets <- unlist(drug.info[validTopSets])
tested.drugs <- na.omit(unique(dmea.sens.df$DrugTreatment))
drugsInValidTopSets <- drugsInValidTopSets[drugsInValidTopSets %in% tested.drugs]
inputDrugs <- unique(unlist(drug.info))[unique(unlist(drug.info)) %in% tested.drugs]
inputFace <- rep("plain", length(inputDrugs))
names(inputFace) <- inputDrugs
inputFace[drugsInValidTopSets] <- "bold"

dot.df <- dmea.sens.df[dmea.sens.df$Drug_set %in% names(drug.info),]
dot.df$Time <- factor(dot.df$Time, levels=timepoints)
if (any(dot.df$FDR_q_value == 0)) {
  dot.df[dot.df$FDR_q_value == 0,]$FDR_q_value <- 0.0001
}
dot.df$minusLogP <- -log(dot.df[,"p_value"], base = 10)
dot.df$minusLogFDR <- -log(dot.df[,"FDR_q_value"], base = 10)
maxAbsNES <- ceiling(max(abs(dot.df$NES)))
dot.plot <- ggplot2::ggplot(
  na.omit(dot.df),
  ggplot2::aes(
    x = DrugTreatment, y = Drug_set, color = NES,
    size = minusLogFDR
  )
) +
  ggplot2::geom_point() +
  ggplot2::scale_y_discrete(limits = setOrder) +
  ggplot2::scale_x_discrete(limits=names(inputFace)) +
  scale_color_gradient2(low="blue",high="red", mid="grey", 
                        limits=c(-maxAbsNES, maxAbsNES)) +
  #viridis::scale_color_viridis() +
  theme_minimal(base_size=12) +
  ggplot2::labs(
    x = "Drug Treatment (Input)",
    y = "Drug Mechanism (Output)",
    color = "NES", size = "-log(FDR)"
  ) + 
  theme(axis.text.y=element_text(face=setFace), 
        axis.text.x=element_text(face=inputFace,
          angle=45, vjust=1, hjust=1),
        legend.box="horizontal") +
  geom_point(data = subset(dot.df, sig), col = "black", stroke = 1.5, shape = 21) +
  facet_wrap(vars(cols = Time))
dot.plot
# most are only in prot and not in RNA
ggplot2::ggsave("Validation_MOAs_dotPlot_facetTime.pdf", dot.plot, width=10, height=3)

# also plot just sig validations as scatter plot over time
validations$Time <- as.numeric(substr(validations$Time, 1, nchar(validations$Time)-1))
validations$Drug_set <- factor(validations$Drug_set, levels=sort(na.omit(unique(validations$Drug_set))))
validation.plot <- ggplot2::ggplot(validations, aes(x=Time, y=NES, color=DrugTreatment)) + 
  geom_point(aes(shape=Drug_set)) + geom_line(linetype="dashed") +
  scale_x_continuous(trans="log10") +
  labs(x="Time (Hours)", y="Normalized Enrichment Score",
       color = "Drug Treatment", shape = "Mechanism") +
  scale_shape_manual(values=1:nlevels(validations$Drug_set)) + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("validatedDrugMechanisms_scatterPlot.pdf", validation.plot, width=5.5, height=3)

### Drug correlations
drugValidations <- drug.corr.sens.df[tolower(drug.corr.sens.df$Drug) == tolower(drug.corr.sens.df$DrugTreatment) &
                                       drug.corr.sens.df$Pearson.q <= 0.05,] # 0
drugValidations$Time <- as.numeric(substr(drugValidations$Time, 1, nchar(drugValidations$Time)-1))
validation.plot <- ggplot2::ggplot(drugValidations, aes(x=Time, y=Pearson.est, color=DrugTreatment)) + 
  geom_point() + geom_line(linetype="dashed") +
  scale_x_continuous(trans="log10") +
  labs(x="Time (Hours)", y="Pearson r",
       color = "Drug Treatment", shape = "Mechanism") + theme_classic(base_size=12) +
  theme(legend.box="horizontal")
ggplot2::ggsave("validatedDrugs_scatterPlot.pdf", validation.plot, width=5.5, height=3)
```


### upset plots to see overlap across drug treatments
```{r plot overlap of results, echo = FALSE}
library(ComplexHeatmap)
# inspired by: https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#upset-making-the-plot
### MOA
# generate list of significant results
sigList <- list()
for (i in unique(unlist(drug.info))) {
  sigList[[i]] <- na.omit(unique(dmea.sens.df[dmea.sens.df$DrugTreatment == i & dmea.sens.df$sig,]$Drug_set))
}

# convert to matrix
m = ComplexHeatmap::make_comb_mat(sigList)
moa.info2 <- moa.info2[order(unique(unlist(drug.info))),]
myCol <- as.list(RColorBrewer::brewer.pal(length(drug.info), "Set3"))
names(myCol) <- names(drug.info)
moaAnnotation <- ComplexHeatmap::HeatmapAnnotation(Mechanism = moa.info2$moa, col = myCol, which="row")
ComplexHeatmap::UpSet(m, right_annotation = moaAnnotation)
ComplexHeatmap::UpSet(m)

### drug correlations
# generate list of significant results
sigList <- list()
for (i in unique(unlist(drug.info))) {
  sigList[[i]] <- na.omit(unique(drug.corr.sens.df[drug.corr.sens.df$DrugTreatment == i & drug.corr.sens.df$Pearson.q <= 0.05,]$Drug))
}

# convert to matrix
m = ComplexHeatmap::make_comb_mat(sigList)
moa.info2 <- moa.info2[order(unique(unlist(drug.info))),]
myCol <- as.list(RColorBrewer::brewer.pal(length(drug.info), "Set3"))
names(myCol) <- names(drug.info)
moaAnnotation <- ComplexHeatmap::HeatmapAnnotation(Mechanism = moa.info2$moa, col = myCol, which="row")
ComplexHeatmap::UpSet(m, right_annotation = moaAnnotation)
ComplexHeatmap::UpSet(m)

# could also repeat for individual timepoints or filtered for "optimal" timepoints (max validation / inhibition of known targets)
```