---
title: "Ex1 Phospho proteomics"
output: html_document
---

Preliminary summary

```{r include=FALSE}
library(MSnSet.utils)
library(dplyr)
library(ggplot2)
library(readxl)

global_crosstab <- read.table("../proteomics/data/global_data/Chr8_UMN1_crosstab_global_gene_original.txt")
phospho_crosstab <- read.table("../proteomics/data/phospho_data/Chr8_UMN1_crosstab_phospho_siteID_original.txt")
phospho_crosstab_prot <- read.table("../proteomics/data/phospho_data/Chr8_UMN1_crosstab_phospho_siteID_prot_original.txt", sep = "\t")

meta <- read_excel("../proteomics/data/PDX Proteomics Exp1 metadata.xlsx") 

# add unique identifier
meta$Tube <- paste(meta$PDX, meta$Drug, meta$`Time point (hr)`, "hr", sep = "_")
tube.types <- unique(meta$Tube)
for (i in 1:length(tube.types)) {
  meta[meta$Tube == tube.types[i],]$Tube <- paste0(meta[meta$Tube == tube.types[i],]$Tube, "_rep", seq(1, nrow(meta[meta$Tube == tube.types[i],])))
}
meta <- as.data.frame(meta)
rownames(meta) <- sub("-", ".", meta$Tube)
rownames(meta) <- sub("-", ".", rownames(meta)) # there are two dashes in JH-2-002 samples
meta$Treatment <- paste0(meta$Drug, " (", meta$`Time point (hr)`, " hrs)")
colnames(meta)[5] <- "Plex"
meta$Plex <- as.character(meta$Plex)

colnames(global_crosstab) <- sub("^X", "", colnames(global_crosstab))
colnames(phospho_crosstab) <- sub("^X", "", colnames(phospho_crosstab))
colnames(phospho_crosstab_prot) <- sub("^data.", "", colnames(phospho_crosstab_prot))

## data only
phospho_prot_mat <- dplyr::select_if(phospho_crosstab_prot, is.numeric)


```


Missing data


```{r}
global_missing <- rowSums(is.na(global_crosstab))
phospho_missing <- rowSums(is.na(phospho_crosstab))
phospho_prot_missing <- rowSums(is.na(phospho_prot_mat))

hist(global_missing)
hist(phospho_missing)
hist(phospho_prot_missing)

## 50 % missingness filter
global_crosstab <- global_crosstab[global_missing < ncol(global_crosstab)/2, ]
phospho_crosstab <- phospho_crosstab[phospho_missing < ncol(phospho_crosstab)/2, ]
phospho_prot_mat <- phospho_prot_mat[phospho_prot_missing < ncol(phospho_crosstab)/2, ]

```


Raw data stats.


```{r}
## row medians
hist(apply(global_crosstab, 1, median, na.rm = T))
hist(apply(phospho_crosstab, 1, median, na.rm = T))
hist(apply(phospho_prot_mat, 1, median, na.rm = T))

global_row_medians <- apply(global_crosstab, 1, median, na.rm = T)
phospho_row_medians <- apply(phospho_crosstab, 1, median, na.rm = T)
phospho_prot_row_medians <- apply(phospho_prot_mat, 1, median, na.rm = T)

global_crosstab <- sweep(global_crosstab, 1, global_row_medians, FUN = '-')
phospho_crosstab <- sweep(phospho_crosstab, 1, phospho_row_medians, FUN = '-')
phospho_prot_mat <- sweep(phospho_prot_mat, 1, phospho_prot_row_medians, FUN = '-')

```



```{r}
table(colnames(global_crosstab) == colnames(phospho_crosstab))
table(colnames(global_crosstab) == colnames(phospho_prot_mat))

## sample medians
hist(apply(global_crosstab, 2, median, na.rm = T))
hist(apply(phospho_crosstab, 2, median, na.rm = T))
hist(apply(phospho_prot_mat, 2, median, na.rm = T))

## Using global coefficients to normalize phospho.
global_sample_coef <- apply(global_crosstab, 2, median, na.rm = T)

global_crosstab <- sweep(global_crosstab, 2, global_sample_coef, FUN = '-')
phospho_crosstab <- sweep(phospho_crosstab, 2, global_sample_coef, FUN = '-')
phospho_prot_mat <- sweep(phospho_prot_mat, 2, global_sample_coef, FUN = '-')

```



```{r}
m_global <- MSnSet(exprs = global_crosstab %>% as.matrix(), 
                   pData = meta[colnames(global_crosstab), ])

m_phospho <- MSnSet(exprs = phospho_crosstab %>% as.matrix(), 
                    pData = meta[colnames(phospho_crosstab), ])

m_phospho_prot <- MSnSet(exprs = phospho_prot_mat %>% as.matrix(), 
                         pData = meta[colnames(phospho_prot_mat), ])

```


Both datasets show strong batch effect


```{r}
dir.create("PCA")
dir.create("before_plex_correction")
temp.path <- "PCA/before_plex_correction/"
phenos <- c("Plex", "Tube", "PDX", "Drug", "Time point (hr)", "Treatment")
for (i in 1:length(phenos)) {
  plot_pca(m_global, phenotype = phenos[i]) + ggtitle("Global PCA")
  ggsave(paste0(temp.path, "Chr8_UMN1_global_PCA_by_", phenos[i], ".pdf"))
  
  plot_pca(m_phospho, phenotype = phenos[i]) + ggtitle("Phospho PCA")
  ggsave(paste0(temp.path,"Chr8_UMN1_phospho_PCA_by_", phenos[i], ".pdf"))
  
  plot_pca(m_phospho_prot, phenotype = phenos[i]) + ggtitle("Phospho prot PCA")
  ggsave(paste0(temp.path, "Chr8_UMN1_phospho_prot_PCA_by_", phenos[i], ".pdf"))
}

```


```{r}
m_global_corrected <- correct_batch_effect_NA(m_global, "Plex", par.prior = T)
m_phospho_corrected <- correct_batch_effect_NA(m_phospho, "Plex", par.prior = T)

m_phospho_prot_corrected <- correct_batch_effect_NA(m_phospho_prot, "Plex", par.prior = T)

```



```{r}
dir.create("PCA/after_plex_correction")
temp.path <- "PCA/after_plex_correction/"
phenos <- c("Plex", "Tube", "PDX", "Drug", "Time point (hr)", "Treatment")
for (i in 1:length(phenos)) {
  plot_pca(m_global_corrected, phenotype = phenos[i]) + ggtitle("Global PCA")
  ggsave(paste0(temp.path, "Chr8_UMN1_global_PCA_by_", phenos[i], ".pdf"))
  
  plot_pca(m_phospho_corrected, phenotype = phenos[i]) + ggtitle("Phospho PCA")
  ggsave(paste0(temp.path,"Chr8_UMN1_phospho_PCA_by_", phenos[i], ".pdf"))
  
  plot_pca(m_phospho_prot_corrected, phenotype = phenos[i]) + ggtitle("Phospho prot PCA")
  ggsave(paste0(temp.path, "Chr8_UMN1_phospho_prot_PCA_by_", phenos[i], ".pdf"))
}


# also filter to focus on specific drug treatments, PDX
PDXs <- unique(meta$PDX)
PDXs <- PDXs[!grepl("reference", PDXs, ignore.case = TRUE)]
drugs <- na.omit(unique(meta$Drug))
for (i in drugs) {
  dir.create(file.path(temp.path, i))
  temp.path2 <- file.path(temp.path, i)
  
  drug.meta <- na.omit(meta[meta$Drug == "DMSO" | meta$Drug == i,])
  drug.samples <- rownames(drug.meta)
  drug_global <- MSnSet(exprs = exprs(m_global_corrected)[, drug.samples], 
                   pData = meta[drug.samples, ])
  drug_phospho <- MSnSet(exprs = exprs(m_phospho_corrected)[, drug.samples], 
                   pData = meta[drug.samples, ])
  drug_phospho_prot <- MSnSet(exprs = exprs(m_phospho_prot_corrected)[, drug.samples], 
                   pData = meta[drug.samples, ])
  
  for (k in 1:length(phenos)) {
  plot_pca(drug_global, phenotype = phenos[k]) + ggtitle("Global PCA")
  ggsave(paste0(temp.path2, "/Chr8_UMN1_global_PCA_by_", phenos[k], ".pdf"))
  
  plot_pca(drug_phospho, phenotype = phenos[k]) + ggtitle("Phospho PCA")
  ggsave(paste0(temp.path2,"/Chr8_UMN1_phospho_PCA_by_", phenos[k], ".pdf"))
  
  plot_pca(drug_phospho_prot, phenotype = phenos[k]) + ggtitle("Phospho prot PCA")
  ggsave(paste0(temp.path2, "/Chr8_UMN1_phospho_prot_PCA_by_", phenos[k], ".pdf"))
  }
  
  # also filter for each PDX
  for (j in PDXs) {
    dir.create(file.path(temp.path2, j))
    temp.path3 <- file.path(temp.path2, j) 
    
    drug.pdx.samples <- rownames(na.omit(drug.meta[drug.meta$PDX == j,]))
    drug_pdx_global <- MSnSet(exprs = exprs(m_global_corrected)[, drug.pdx.samples], 
                   pData = meta[drug.pdx.samples, ])
    drug_pdx_phospho <- MSnSet(exprs = exprs(m_phospho_corrected)[, drug.pdx.samples], 
                   pData = meta[drug.pdx.samples, ])
    drug_pdx_phospho_prot <- MSnSet(exprs = exprs(m_phospho_prot_corrected)[, drug.pdx.samples], 
                   pData = meta[drug.pdx.samples, ])
    
    for (k in 1:length(phenos)) {
      plot_pca(drug_pdx_global, phenotype = phenos[k]) + ggtitle("Global PCA")
      ggsave(paste0(temp.path3, "/Chr8_UMN1_global_PCA_by_", phenos[k], ".pdf"))
  
      plot_pca(drug_pdx_phospho, phenotype = phenos[k]) + ggtitle("Phospho PCA")
      ggsave(paste0(temp.path3,"/Chr8_UMN1_phospho_PCA_by_", phenos[k], ".pdf"))
  
      plot_pca(drug_pdx_phospho_prot, phenotype = phenos[k]) + ggtitle("Phospho prot PCA")
      ggsave(paste0(temp.path3, "/Chr8_UMN1_phospho_prot_PCA_by_", phenos[k], ".pdf"))
    }
  }
}
```

Push to synapse.

```{r}
write.table(exprs(m_global_corrected), 
            file = "data/global_data/Chr8_UMN1_crosstab_global_gene_corrected.txt",
            quote=F, sep="\t")

write.table(exprs(m_phospho_corrected), 
            file = "data/phospho_data/Chr8_UMN1_crosstab_phospho_SiteID_corrected.txt",
            quote=F, sep="\t")


phospho_prot_corrected <- exprs(m_phospho_prot_corrected) %>%
  as.data.frame() %>%
  mutate(feature = rownames(.))
mapping_df <- phospho_crosstab_prot %>%
  mutate(feature = rownames(.)) %>%
  select(feature, Peptide_kstar, Protein_kstar, SiteID)

phospho_prot_corrected <- merge(phospho_prot_corrected, mapping_df, by = "feature")
rownames(phospho_prot_corrected) <- phospho_prot_corrected$feature
phospho_prot_corrected <- phospho_prot_corrected %>% select(-feature) %>%
  select(SiteID, Peptide_kstar, Protein_kstar, everything())

colnames(phospho_prot_corrected) <- sub("(^[0-9].*$)", "data:\\1", colnames(phospho_prot_corrected))
write.table(phospho_prot_corrected, 
            file = "data/phospho_data/Chr8_UMN1_crosstab_phospho_SiteID_prot_corrected.txt",
            sep="\t")

```


```{r}
plex_global <- limma_gen(m_global, "~Plex", "Plex")
plex_phospho <- limma_gen(m_phospho, "~Plex", "Plex")

plex_global_corrected <- limma_gen(m_global_corrected, "~Plex", "Plex")
plex_phospho_corrected <- limma_gen(m_phospho_corrected, "~Plex", "Plex")


```



```{r}
hist(plex_global$P.Value)
hist(plex_global_corrected$P.Value)

hist(plex_phospho$P.Value)
hist(plex_phospho_corrected$P.Value)

```


